import type { Extra } from './soorten'

// Per module: kernvraag, matn met vertaling/woordanker, toepassingsopdracht.

/* EXTRA: per module een kernvraag (need-to-know), matn-fragment(en) met
   vertaling, woordanker en verantwoording, en een toepassingsopdracht. */
export const EXTRA: Record<string, Extra> = {

u1:{kern:'Waarom is "welke school volg je" geen smaakvraag maar een methodevraag?',
 matn:[{ar:'كُلُّ أَحَدٍ يُؤْخَذُ مِنْ قَوْلِهِ وَيُتْرَكُ، إِلَّا صَاحِبَ هَذَا الْقَبْرِ',
  nl:'Van ieders woord wordt genomen en gelaten, behalve van hem die in dit graf ligt.',
  bron:'Traditioneel aan Malik toegeschreven, in Medina bij het graf van de Profeet \u2014 maar zonder keten. M\u00e9t keten is de uitspraak overgeleverd van al-Hakam ibn \u2018Utayba en van Mujahid, onder meer bij Ibn \u2018Abd al-Barr, <em>Jami\u2018 bayan al-\u2018ilm</em> 2/925\u2013926. Dat de toeschrijving aan Malik zelf niet hard is, maakt haar als eerste les alleen maar treffender.',
  g:[['يُؤْخَذُ','wordt genomen (passief)'],['يُتْرَكُ','wordt gelaten'],['إِلَّا','behalve'],['صَاحِبَ هَذَا الْقَبْرِ','de bewoner van dit graf']],
  w:'De stichter van de school formuleert zelf de grens van zijn eigen gezag. Dat is het beste tegengif tegen de gedachte dat een madhhab volgen hetzelfde is als een persoon vergoddelijken \u2014 en het verklaart waarom de school binnen zichzelf altijd meningsverschil heeft toegelaten.'}],
 doe:'Noem één religieuze regel waarvan je altijd hebt aangenomen dat die vaststaat, en waarvan je nu vermoedt dat het een schoolpositie is. Schrijf op waar je die regel vandaan hebt \u2014 van thuis, van de moskee, van een boek \u2014 en wat je zou moeten weten om dat te verifi\u00ebren.'},

u2:{kern:'Welke bronnen tellen mee, en wie bepaalt dat?',
 matn:[{ar:'يَا أَيُّهَا الَّذِينَ آمَنُوا أَطِيعُوا اللَّهَ وَأَطِيعُوا الرَّسُولَ وَأُولِي الْأَمْرِ مِنكُمْ ۖ فَإِن تَنَازَعْتُمْ فِي شَيْءٍ فَرُدُّوهُ إِلَى اللَّهِ وَالرَّسُولِ',
  nl:'Jullie die geloven, gehoorzaamt God en gehoorzaamt de boodschapper en hen onder jullie die gezag hebben. En als jullie over iets twisten, legt het dan voor aan God en de boodschapper.',
  bron:'Koran 4:59 (soera al-Nisa\u2019). In de usul-literatuur het klassieke bewijsvers voor de rangorde van de bronnen.',
  g:[['أَطِيعُوا','gehoorzaamt'],['أُولِي الْأَمْرِ','zij die gezag hebben'],['تَنَازَعْتُمْ','jullie twisten'],['فَرُدُّوهُ','legt het dan terug/voor']],
  w:'Juristen lezen hier de vier onbetwiste bronnen in: God (Koran), de boodschapper (Sunna), de gezagsdragers (ijma\u2018), en het \u201cterugleggen\u201d bij twist (qiyas als redenering naar de bron toe). Let op hoe zwaar die laatste stap leunt op interpretatie \u2014 precies daar begint het schoolverschil.'}],
 doe:'Vergelijk de bronnenhi\u00ebrarchie met de evidence-piramide die je in de geneeskunde gebruikt. Waar loopt de analogie, en waar breekt zij? Formuleer in twee zinnen wat volgens jou het equivalent is van \u201cexpert opinion\u201d in de fiqh.'},

u3:{kern:'Waarom telt een handeling die duizenden mensen tegelijk verrichten zwaarder dan een keten van namen?',
 matn:[{ar:'تَرَكْتُ فِيكُمْ أَمْرَيْنِ لَنْ تَضِلُّوا مَا تَمَسَّكْتُمْ بِهِمَا: كِتَابَ اللَّهِ وَسُنَّةَ نَبِيِّهِ',
  nl:'Ik heb onder jullie twee zaken achtergelaten; zolang jullie je daaraan vasthouden zullen jullie niet dwalen: het boek van God en de sunna van Zijn profeet.',
  bron:'Muwatta\u2019, kitab al-qadar. Malik levert dit over zonder volledige keten \u2014 een <em>balagh</em> (\u201chet heeft mij bereikt\u201d), naar de latere hadithcriteria dus zwak.',
  g:[['تَرَكْتُ','ik heb achtergelaten'],['لَنْ تَضِلُّوا','jullie zullen niet dwalen'],['تَمَسَّكْتُمْ','jullie je vasthouden'],['سُنَّةَ','gebaande weg, sunna']],
  w:'Uitgerekend een van de bekendste teksten van de school is naar latere maatstaven onvoldoende gedocumenteerd. Voor Malik was dat geen bezwaar: de inhoud werd gedragen door de onafgebroken praktijk van Medina. Wie dit begrijpt, begrijpt \u2018amal ahl al-Madina.'}],
 doe:'Beschrijf een klinische regel die je hanteert zonder dat er een RCT onder ligt \u2014 iets wat \u201cwij hier zo doen\u201d en aantoonbaar werkt. Wat maakt die praktijkkennis betrouwbaar, en waar zit haar kwetsbaarheid? Dat is precies het debat tussen Malik en al-Shafi\u2018i.'},

u4:{kern:'Hoe kan iets dat op zichzelf mag, toch verboden worden?',
 matn:[{ar:'وَلَا تَسُبُّوا الَّذِينَ يَدْعُونَ مِن دُونِ اللَّهِ فَيَسُبُّوا اللَّهَ عَدْوًا بِغَيْرِ عِلْمٍ',
  nl:'En scheldt niet op hen die anderen dan God aanroepen, want dan zouden zij uit vijandigheid en zonder kennis op God schelden.',
  bron:'Koran 6:108 (soera al-An\u2018am). Het standaardbewijs voor <em>sadd al-dhara\u2019i\u2019</em> in de Malikitische usul.',
  g:[['لَا تَسُبُّوا','scheldt niet'],['مِن دُونِ اللَّهِ','buiten God om'],['عَدْوًا','uit vijandigheid, overschrijdend'],['بِغَيْرِ عِلْمٍ','zonder kennis']],
  w:'Het afwijzen van afgoderij is niet alleen toegestaan maar geboden \u2014 en toch wordt één uitingsvorm ervan verboden, uitsluitend vanwege het voorzienbare gevolg. Dat is het hele beginsel in één vers: de handeling wordt beoordeeld op haar keten van effecten, niet alleen op zichzelf.'}],
 doe:'Sadd al-dhara\u2019i\u2019 lijkt sterk op het voorzorgsbeginsel. Noem een maatregel in de zorg die op precies deze logica berust, en één waarbij de logica is doorgeschoten. Wat onderscheidt de twee?'},

u5:{kern:'Waarom is het verschil tussen "mag niet" en "beter van niet" geen woordenspel?',
 matn:[{ar:'لَا يُكَلِّفُ اللَّهُ نَفْسًا إِلَّا وُسْعَهَا',
  nl:'God belast een ziel niet boven haar vermogen.',
  bron:'Koran 2:286 (slot van soera al-Baqara). Het fundament onder het hele begrip <em>taklif</em> \u2014 verplichtingstelling.',
  g:[['يُكَلِّفُ','belast, legt een verplichting op'],['نَفْسًا','een ziel, een persoon'],['وُسْعَهَا','haar vermogen, haar ruimte']],
  w:'Het woord <em>taklif</em> in \u201chukm taklifi\u201d komt hiervandaan. De vijf categorie\u00ebn zijn dus geen willekeurige indeling maar de uitwerking van één gedachte: verplichting is begrensd door vermogen. Alles wat later over ziekte, noodzaak en dispensatie volgt, hangt aan dit vers.'}],
 doe:'Neem een handeling waarvan je je afvraagt hoe zwaar zij weegt \u2014 een gewoonte, een nalaten. Plaats haar in de vijf categorie\u00ebn en schrijf op welk gegeven je zou moeten opzoeken om die plaatsing te verantwoorden.'},

m1:{kern:'Wie was Malik, en waarom staat niet zijn eigen boek maar dat van zijn leerling centraal?',
 matn:[{ar:'إِنَّمَا أَنَا بَشَرٌ أُخْطِئُ وَأُصِيبُ، فَانْظُرُوا فِي رَأْيِي، فَكُلُّ مَا وَافَقَ الْكِتَابَ وَالسُّنَّةَ فَخُذُوا بِهِ، وَكُلُّ مَا لَمْ يُوَافِقِ الْكِتَابَ وَالسُّنَّةَ فَاتْرُكُوهُ',
  nl:'Ik ben slechts een mens; ik vergis mij en ik tref het. Onderzoekt daarom mijn mening: alles wat overeenstemt met het boek en de sunna, neemt dat aan; en alles wat er niet mee overeenstemt, laat dat.',
  bron:'Toegeschreven aan Malik ibn Anas; overgeleverd in Ibn \u2018Abd al-Barr, <em>Jami\u2018 bayan al-\u2018ilm wa-fadlih</em>.',
  g:[['بَشَرٌ','mens, sterveling'],['أُخْطِئُ','ik maak fouten'],['أُصِيبُ','ik tref het juiste'],['وَافَقَ','overeenstemde met'],['فَاتْرُكُوهُ','laat het dan']],
  w:'Vergelijk met de eerste week: dezelfde man, dezelfde beweging. Het gezag van de imam is instrumenteel, niet absoluut. Precies daarom kon de school na hem doorgroeien \u2014 en kon Ibn al-Qasim op punten afwijken zonder dat dat als verraad gold.'}],
 doe:'Zoek op wat de <span class="ar">المدوّنة</span> <em>Mudawwana</em> is en waarom Ibn al-Qasim daarin de sleutelfiguur is. Schrijf in drie zinnen op wat het voor jouw manier van citeren betekent dat \u201cde Malikitische positie\u201d vaak niet van Malik zelf komt.'},

m2:{kern:'Welke boeken vormen de trap, en waar zet jij je voet?',
 matn:[{ar:'وَبَعْدُ فَالْعَوْنُ مِنَ اللهِ الْمَجِيدْ ¶ فِي نَظْمِ أَبْيَاتٍ لِلْأُمِّيِّ تُفِيدْ\nفِي عَقْدِ الْأَشْعَرِيِّ وَفِقْهِ مَالِكْ ¶ وَفِي طَرِيقَةِ الْجُنَيْدِ السَّالِكْ',
  nl:'En voorts: de hulp komt van God de Glorierijke, bij het dichten van verzen die de ongeletterde van nut zijn \u2014 in de geloofsleer van al-Ash\u2018ari, de fiqh van Malik, en de weg van al-Junayd die de tocht gaat.',
  bron:'Ibn \u2018Ashir, <em>al-Murshid al-mu\u2018in</em>, verzen 4\u20135 van 317. Het meest geciteerde couplet van de Maghreb.',
  g:[['وَبَعْدُ','en voorts (overgangsformule)'],['نَظْمِ','het dichten, versificatie'],['لِلْأُمِّيِّ','voor de ongeletterde'],['عَقْدِ','geloofsleer, wat men vastknoopt'],['السَّالِكْ','de reiziger op het pad']],
  w:'Let op het woord <em>li-l-ummi</em>: dit werk is uitdrukkelijk geschreven voor wie niet kan lezen, om te worden gememoriseerd en gehoord. Dat verklaart de radjaz-versmaat. En het tweede vers is de complete definitie van het Marokkaanse religieuze bestel in veertien woorden.'}],
 doe:'Lees de twee verzen hardop tot je ze zonder tekst kunt zeggen. Schrijf daarna op welke van de drie zuilen \u2014 fiqh, \u2018aqida, tasawwuf \u2014 in jouw opvoeding het sterkst en welke het zwakst is meegegeven, en wat dat verklaart.'},

m3:{kern:'Waarom bidt en wast men in Marokko net iets anders dan in Egypte?',
 matn:[{ar:'يَا أَيُّهَا الَّذِينَ آمَنُوا إِذَا قُمْتُمْ إِلَى الصَّلَاةِ فَاغْسِلُوا وُجُوهَكُمْ وَأَيْدِيَكُمْ إِلَى الْمَرَافِقِ وَامْسَحُوا بِرُءُوسِكُمْ وَأَرْجُلَكُمْ إِلَى الْكَعْبَيْنِ',
  nl:'Jullie die geloven, wanneer jullie je opmaken voor het gebed, wast dan jullie gezicht en jullie handen tot de ellebogen, en strijkt over jullie hoofd, en jullie voeten tot de enkels.',
  bron:'Koran 5:6 (soera al-Ma\u2019ida). Het wudu-vers.',
  g:[['فَاغْسِلُوا','wast dan'],['الْمَرَافِقِ','de ellebogen'],['وَامْسَحُوا','en strijkt over'],['بِرُءُوسِكُمْ','over jullie hoofden'],['الْكَعْبَيْنِ','de twee enkels']],
  w:'Het hele schoolverschil hangt hier aan één letter: de <em>b\u0101\u2019</em> in <span class="ar">برؤوسكم</span> <em>bi-ru\u2019usikum</em>. Lees je haar als versterkend, dan moet het hele hoofd worden afgestreken \u2014 de Malikitische positie. Lees je haar als partitief (<span class="ar">للتبعيض</span> <em>li-l-tab\u2018id</em>), dan volstaat een deel \u2014 de Shafi\u2018itische. Eén partikel, twee praktijken, beide filologisch verdedigbaar.'}],
 doe:'Ga na hoe jij zelf de wudu verricht. Welke handelingen doe je uit gewoonte zonder te weten of ze verplicht, aanbevolen of overbodig zijn? Kies er één uit en zoek haar Malikitische status op.'},

m4:{kern:'Wat maakt een contract of een huwelijk in deze school geldig \u2014 en wat maakt het ontbindbaar?',
 matn:[{ar:'يَا أَيُّهَا الَّذِينَ آمَنُوا إِذَا تَدَايَنتُم بِدَيْنٍ إِلَىٰ أَجَلٍ مُّسَمًّى فَاكْتُبُوهُ',
  nl:'Jullie die geloven, wanneer jullie elkaar een schuld aangaan voor een vastgestelde termijn, legt die dan schriftelijk vast.',
  bron:'Koran 2:282, het langste vers van de Koran (<em>ayat al-dayn</em>).',
  g:[['تَدَايَنتُم','jullie zijn een schuldverhouding aangegaan'],['أَجَلٍ مُّسَمًّى','een bij name genoemde termijn'],['فَاكْتُبُوهُ','legt het dan schriftelijk vast']],
  w:'Dit is het vroegste bewijs dat de openbaring onzekerheid in transacties actief wil terugdringen. Het begrip <span class="ar">\u063a\u0631\u0631</span> <em>gharar</em> is de systematisering daarvan. Dat het langste vers over documentatie van schulden gaat, zegt iets over waar de wetgever risico zag.'}],
 doe:'De Marokkaanse Mudawwana van 2004 leunt op de Malikitische darar-leer. Schrijf op wat je daarvan tot nu toe wist en waar dat vandaan kwam. Formuleer daarna één vraag die je aan een jurist zou willen stellen.'},

m5:{kern:'Wat is het verschil tussen "de islam zegt", "de rechter besliste" en "de staat bepaalde"?',
 matn:[{ar:'إِنَّمَا أَنَا بَشَرٌ، وَإِنَّكُمْ تَخْتَصِمُونَ إِلَيَّ، وَلَعَلَّ بَعْضَكُمْ أَنْ يَكُونَ أَلْحَنَ بِحُجَّتِهِ مِنْ بَعْضٍ فَأَقْضِيَ لَهُ عَلَىٰ نَحْوِ مَا أَسْمَعُ، فَمَنْ قَضَيْتُ لَهُ بِحَقِّ أَخِيهِ شَيْئًا فَلَا يَأْخُذْهُ',
  nl:'Ik ben slechts een mens, en jullie leggen mij geschillen voor. Misschien is de een van jullie welsprekender in zijn pleidooi dan de ander, zodat ik in zijn voordeel oordeel naar wat ik hoor. Aan wie ik dus iets toewijs dat het recht van zijn broeder is: laat hij het niet nemen.',
  bron:'Muwatta\u2019, kitab al-aqdiya; ook bij al-Bukhari en Muslim.',
  g:[['تَخْتَصِمُونَ','jullie voeren een geschil'],['أَلْحَنَ بِحُجَّتِهِ','welsprekender in zijn argument'],['فَأَقْضِيَ','zodat ik oordeel'],['نَحْوِ مَا أَسْمَعُ','de strekking van wat ik hoor']],
  w:'Een rechterlijk vonnis werkt naar buiten en verandert de werkelijkheid niet. Zelfs het oordeel van de Profeet zelf, zegt de tekst, bindt de rechtsverhouding maar niet het geweten. Al-Qarafi bouwt hierop zijn hele onderscheid tussen fatwa, vonnis en overheidsdaad.'}],
 doe:'Denk aan een situatie waarin een formeel juiste beslissing materieel onrechtvaardig uitpakte \u2014 in de zorg, in een bestuur, in een familie. Wat had de tekst hierboven daar te zeggen?'},

a1:{kern:'Wat wordt er in deze traditie precies van je verwacht dat je gelooft?',
 matn:[{ar:'بَابُ مَا تَنْطِقُ بِهِ الْأَلْسِنَةُ وَتَعْتَقِدُهُ الْأَفْئِدَةُ مِنْ وَاجِبِ أُمُورِ الدِّيَانَاتِ: مِنْ ذَلِكَ الْإِيمَانُ بِالْقَلْبِ وَالنُّطْقُ بِاللِّسَانِ أَنَّ اللهَ إِلَهٌ وَاحِدٌ لَا إِلَهَ غَيْرُهُ',
  nl:'Hoofdstuk over hetgeen de tongen uitspreken en de harten geloven van de verplichte zaken van de godsdienst. Daartoe behoort het geloven met het hart en het uitspreken met de tong dat God één God is en dat er geen god is buiten Hem.',
  bron:'Ibn Abi Zayd al-Qayrawani, <em>al-Risala</em>, openingshoofdstuk.',
  g:[['تَنْطِقُ بِهِ','waarmee spreekt'],['الْأَفْئِدَةُ','de harten (mv. van fu\u2019ad)'],['وَاجِبِ','het verplichte deel van'],['النُّطْقُ','het uitspreken']],
  w:'Merk de volgorde op: eerst de tong, dan het hart, en het geloof wordt gedefinieerd als beide tegelijk. Het is ook het bewijs dat een <span class="ar">\u0641\u0642\u0647</span> <em>fiqh</em>-handboek in deze traditie standaard met geloofsleer opent \u2014 recht en dogma zijn niet gescheiden vakken.'}],
 doe:'Ibn \u2018Ashir noemt drie zuilen, Ibn Abi Zayd opent met de \u2018aqida. Schrijf op welke vragen over geloofsleer je in je leven feitelijk hebt vermeden, en waarom.'},

a2:{kern:'Kun je geloofsleer opbouwen zonder in een cirkelredenering te belanden?',
 matn:[{ar:'اعْلَمْ أَنَّ الْحُكْمَ الْعَقْلِيَّ يَنْحَصِرُ فِي ثَلَاثَةِ أَقْسَامٍ: الْوُجُوبِ وَالِاسْتِحَالَةِ وَالْجَوَازِ. فَالْوَاجِبُ مَا لَا يُتَصَوَّرُ فِي الْعَقْلِ عَدَمُهُ، وَالْمُسْتَحِيلُ مَا لَا يُتَصَوَّرُ فِي الْعَقْلِ وُجُودُهُ، وَالْجَائِزُ مَا يَصِحُّ فِي الْعَقْلِ وُجُودُهُ وَعَدَمُهُ',
  nl:'Weet dat het rationele oordeel zich beperkt tot drie categorie\u00ebn: noodzakelijkheid, onmogelijkheid en mogelijkheid. Het noodzakelijke is dat waarvan het verstand zich de afwezigheid niet kan voorstellen; het onmogelijke is dat waarvan het verstand zich het bestaan niet kan voorstellen; het mogelijke is dat waarvan het verstand zowel bestaan als afwezigheid toelaat.',
  bron:'Al-Sanusi, <em>Umm al-barahin</em>, openingszin.',
  g:[['اعْلَمْ','weet, besef'],['الْحُكْمَ الْعَقْلِيَّ','het oordeel van het verstand'],['يَنْحَصِرُ','beperkt zich tot'],['يُتَصَوَّرُ','wordt voorgesteld, gedacht'],['عَدَمُهُ','zijn afwezigheid']],
  w:'De hele Maghrebijnse geloofsleer begint niet met een tekst maar met een logische distinctie. Dat is een bewuste keuze: het fundament van de openbaring moet buiten de openbaring liggen, anders is het bewijs circulair. Wie deze zin beheerst, heeft de sleutel tot alles wat volgt.'}],
 doe:'Pas de drie categorie\u00ebn toe op iets uit je eigen vak: noem één ding dat noodzakelijk waar is, één dat onmogelijk is, en één dat mogelijk is. Merk op hoe zelden de derde categorie in het publieke debat wordt gebruikt.'},

a3:{kern:'Wat betekent het precies om te zeggen dat God één is?',
 matn:[{ar:'فَمِمَّا يَجِبُ لِمَوْلَانَا عَزَّ وَجَلَّ عِشْرُونَ صِفَةً وَهِيَ: الْوُجُودُ، وَالْقِدَمُ، وَالْبَقَاءُ، وَمُخَالَفَتُهُ تَعَالَى لِلْحَوَادِثِ، وَقِيَامُهُ تَعَالَى بِنَفْسِهِ، وَالْوَحْدَانِيَّةُ',
  nl:'Tot hetgeen noodzakelijk is voor onze Heer behoren twintig eigenschappen, waaronder: het bestaan, de beginloosheid, het voortduren, Zijn ongelijkheid aan het geschapene, Zijn zelfgenoegzaamheid, en de eenheid.',
  bron:'Al-Sanusi, <em>Umm al-barahin</em>. Tussen de openingsdistinctie en deze zin staat nog de scharnierpassage die het rationele onderscheid tot religieuze plicht maakt: iedere toerekeningsvatbare moet weten wat voor God noodzakelijk, onmogelijk en mogelijk is, en hetzelfde voor de gezanten.',
  g:[['يَجِبُ','is noodzakelijk voor'],['الْقِدَمُ','beginloosheid'],['الْبَقَاءُ','voortduren, eindeloosheid'],['مُخَالَفَتُهُ','Zijn verschil, ongelijkheid'],['الْحَوَادِثِ','het ontstane, het geschapene'],['الْوَحْدَانِيَّةُ','de eenheid']],
  w:'De eerste zes van de twintig. Vier van deze zes zijn <em>ontkenningen</em>: zij zeggen wat God niet is. Dat is geen theologische armoede maar methode \u2014 de weg van <span class="ar">تنزيه</span> <em>tanzih</em>, waarbij het positieve spreken over God zo beperkt mogelijk wordt gehouden om antropomorfisme te vermijden.'}],
 doe:'Schrijf de zes uit het hoofd op, in het Arabisch of in vertaling. Kies er daarna één uit die je nooit expliciet had doordacht, en formuleer in eigen woorden welk misverstand die eigenschap uitsluit.'},

a4:{kern:'Als God alles schept, in welke zin is mijn daad dan van mij?',
 matn:[{ar:'لَهَا مَا كَسَبَتْ وَعَلَيْهَا مَا اكْتَسَبَتْ',
  nl:'Voor haar is wat zij verworven heeft, en tegen haar is wat zij zich verworven heeft.',
  bron:'Koran 2:286, hetzelfde slotvers als in week vijf. Bron van de term <em>kasb</em>.',
  g:[['لَهَا','ten gunste van haar'],['كَسَبَتْ','zij verwierf'],['عَلَيْهَا','ten laste van haar'],['اكْتَسَبَتْ','zij verwierf voor zichzelf (vorm VIII)']],
  w:'Twee vormen van hetzelfde werkwoord in één zin, en die keuze is geen stijl. De klassieke exegese leest in de achtste stam een grotere eigen inspanning \u2014 het goede overkomt de mens eerder, het kwade wordt actiever nagejaagd. Het theologische begrip <span class="ar">\u0643\u0633\u0628</span> <em>kasb</em> is uit precies dit werkwoord gebouwd.'}],
 doe:'Noteer hoe je zelf, in de praktijk, omgaat met de spanning tussen \u201chet is bepaald\u201d en \u201cik ben verantwoordelijk\u201d \u2014 bij een patiënt die alles goed deed en toch ziek werd, of bij een uitkomst die je niet in de hand had.'},

b1:{kern:'Wat bedoelen we als we zeggen "er staat in de Koran"?',
 matn:[{ar:'مَٰلِكِ يَوْمِ ٱلدِّينِ\nمَلِكِ يَوْمِ ٱلدِّينِ',
  nl:'Meester over de dag des oordeels. \u2014 Koning van de dag des oordeels.',
  bron:'Koran 1:4. Boven de lezing van Hafs van \u2018Asim (oostelijke standaard), onder die van Warsh van Nafi\u2018 (Maghreb, dus jouw lezing).',
  g:[['مَٰلِك','bezitter, heerser (deelwoord)'],['مَلِك','koning (zelfstandig naamwoord)'],['يَوْمِ ٱلدِّينِ','de dag van het oordeel']],
  w:'Twee canonieke lezingen, twee betekenissen, geen fout. De keten van Warsh loopt via Nafi\u2018 van Medina \u2014 dezelfde stad die het recht van de Maghreb leverde. Vanaf nu weet je: wie zegt \u201cer staat\u201d, citeert altijd een lezing.'}],
 doe:'Pak een mushaf uit je huis en kijk op het colofon welke overlevering het is. Sla soera al-Fatiha op en kijk of daar <em>malik</em> of <em>malik</em> met alif staat. Noteer wat je vindt.'},

b2:{kern:'Hoe leest een jurist een vers \u2014 en wat mag hij er niet mee doen?',
 matn:[{ar:'هُوَ الَّذِي أَنزَلَ عَلَيْكَ الْكِتَابَ مِنْهُ آيَاتٌ مُّحْكَمَاتٌ هُنَّ أُمُّ الْكِتَابِ وَأُخَرُ مُتَشَابِهَاتٌ',
  nl:'Hij is het die het boek tot jou heeft neergezonden. Daarin zijn ondubbelzinnige verzen \u2014 zij zijn de moeder van het boek \u2014 en andere die meerduidig zijn.',
  bron:'Koran 3:7 (soera Al \u2018Imran). De zelfbeschrijving waarop de hele exegetische methode rust.',
  g:[['أَنزَلَ','heeft neergezonden'],['مُّحْكَمَاتٌ','vastgestelde, ondubbelzinnige'],['أُمُّ الْكِتَابِ','de moeder, de kern van het boek'],['مُتَشَابِهَاتٌ','op elkaar lijkende, meerduidige']],
  w:'De tekst verklaart zichzelf niet uniform leesbaar. Dat is de grondslag van <span class="ar">\u062a\u0623\u0648\u064a\u0644</span> <em>ta\u2019wil</em>: het meerduidige wordt gelezen in het licht van het ondubbelzinnige, nooit andersom. Precies deze regel scheidt de Ash\u2018aritische omgang met antropomorfe verzen van de letterlijke.'}],
 doe:'Zoek een commentaar bij dit vers \u2014 al-Qurtubi is online in het Arabisch beschikbaar \u2014 en kijk hoeveel ruimte hij besteedt aan de vraag waar de zin ophoudt: bij \u201cbehalve God\u201d of bij \u201cen zij die verankerd zijn in kennis\u201d. Die komma bepaalt een heel theologisch programma.'},

b3:{kern:'Hoe weet je of een overlevering betrouwbaar is?',
 matn:[{ar:'الْإِسْنَادُ مِنَ الدِّينِ، وَلَوْلَا الْإِسْنَادُ لَقَالَ مَنْ شَاءَ مَا شَاءَ',
  nl:'De overleveringsketen behoort tot de religie; en zonder de keten zou wie wilde zeggen wat hij wilde.',
  bron:'\u2018Abdallah ibn al-Mubarak (gestorven 181/797), aangehaald door Muslim in de inleiding van zijn <em>Sahih</em>.',
  g:[['الْإِسْنَادُ','het steunen, de keten'],['لَوْلَا','ware het niet dat'],['مَنْ شَاءَ','wie maar wilde'],['مَا شَاءَ','wat hij maar wilde']],
  w:'Dit is een van de scherpste vroege formuleringen van de bronvereiste, ruim voor de moderne voetnoot — al kende ook de Griekse geschiedschrijving en de Alexandrijnse filologie hun eigen vormen van bronverantwoording. De uitspraak legt ook de grens bloot: de keten toetst de <em>overdracht</em>, niet zonder meer de inhoud.'}],
 doe:'Neem een religieuze uitspraak die je op sociale media of in een preek hebt gehoord en waarvan je de herkomst niet kent. Zoek uit of er een bron bij hoort. Schrijf op hoeveel moeite dat kostte.'},

b4:{kern:'Waarom aanvaardt jouw school een overlevering die anderen zwak noemen?',
 matn:[{ar:'مَالِكٌ، عَنْ عَمْرِو بْنِ يَحْيَى الْمَازِنِيِّ، عَنْ أَبِيهِ، أَنَّ رَسُولَ اللهِ صَلَّى اللهُ عَلَيْهِ وَسَلَّمَ قَالَ: لَا ضَرَرَ وَلَا ضِرَارَ',
  nl:'Malik, van \u2018Amr ibn Yahya al-Mazini, van zijn vader: dat de boodschapper van God heeft gezegd: geen schade en geen schadetoebrenging.',
  bron:'Muwatta\u2019, kitab al-aqdiya. De keten stopt bij Yahya al-Mazini, een opvolger \u2014 het is dus een <em>mursal</em>: de metgezel ontbreekt.',
  g:[['عَنْ','van, via'],['أَبِيهِ','zijn vader'],['ضَرَرَ','schade'],['ضِرَارَ','schadetoebrenging, wederzijds benadelen']],
  w:'Bekijk de keten zelf, want daar zit de les. Naar latere maatstaven is dit zwak. Toch is het een van de meest geciteerde teksten van de hele islamitische rechtsleer en de basis van de regel <span class="ar">الضرر يُزال</span> <em>al-darar yuzal</em>. Ibn \u2018Abd al-Barr onderscheidt <span class="ar">\u0636\u0631\u0631</span> <em>darar</em> \u2014 schade waar jij voordeel bij hebt \u2014 van <span class="ar">ضِرار</span> <em>dirar</em>, schade zonder enig voordeel.'}],
 doe:'Dit fragment draagt straks het hele vijfde spoor. Schrijf nu al op: welke medische beslissing uit je praktijk zou je met \u201cgeen schade en geen schadetoebrenging\u201d kunnen verantwoorden, en waar wringt de regel?'},

t1:{kern:'Waar dient de wet uiteindelijk toe \u2014 en mag je dat weten?',
 matn:[{ar:'مَن قَتَلَ نَفْسًا بِغَيْرِ نَفْسٍ أَوْ فَسَادٍ فِي الْأَرْضِ فَكَأَنَّمَا قَتَلَ النَّاسَ جَمِيعًا وَمَنْ أَحْيَاهَا فَكَأَنَّمَا أَحْيَا النَّاسَ جَمِيعًا',
  nl:'Wie een ziel doodt, anders dan wegens een ziel of verderf op aarde, is als iemand die alle mensen heeft gedood; en wie haar laat leven, is als iemand die alle mensen heeft laten leven.',
  bron:'Koran 5:32 (soera al-Ma\u2019ida). Het kernbewijs voor <em>hifz al-nafs</em>, het behoud van leven.',
  g:[['نَفْسًا','een ziel, een mens'],['فَسَادٍ','verderf, ontwrichting'],['فَكَأَنَّمَا','dan is het als of'],['أَحْيَاهَا','hij deed haar leven']],
  w:'De redenering is universaliserend: het individuele leven staat voor alle leven. Dat is de sterkste tekstuele basis onder de stelling dat behoud van leven tot de <span class="ar">\u0636\u0631\u0648\u0631\u064a\u0627\u062a</span> <em>daruriyyat</em> behoort, en daarmee onder vrijwel alles wat je in dit spoor tegenkomt.'}],
 doe:'Formuleer je eigen beroepsethiek in één zin, zonder religieus vocabulaire. Leg die naast de vijf daruriyyat. Welke van de vijf dekt jouw zin, en welke mist zij?'},

t2:{kern:'Wat mag er wijken als het moet \u2014 en hoe ver?',
 matn:[{ar:'تَدَاوَوْا عِبَادَ اللهِ، فَإِنَّ اللهَ لَمْ يَضَعْ دَاءً إِلَّا وَضَعَ لَهُ دَوَاءً',
  nl:'Laat u behandelen, dienaren van God, want God heeft geen ziekte gegeven zonder er een geneesmiddel voor te geven \u2014 op \u00e9\u00e9n kwaal na: de ouderdom.',
  bron:'Abu Dawud 3855, al-Tirmidhi 2038 en Ibn Maja 3436, in verschillende bewoordingen. Alle drie besluiten met de uitzondering <span class="ar">\u0625\u0644\u0627 \u0627\u0644\u0647\u064e\u0631\u064e\u0645</span> \u2014 <em>illa al-haram</em>, behalve de ouderdom.',
  g:[['تَدَاوَوْا','laat u behandelen (gebiedende wijs, vorm VI)'],['دَاءً','ziekte'],['دَوَاءً','geneesmiddel'],['لَمْ يَضَعْ','heeft niet gelegd, niet ingesteld']],
  w:'Let op de grammaticale spiegeling van <em>da\u2019</em> en <span class="ar">دواء</span> <em>dawa\u2019</em>: dezelfde wortelstructuur, tegengestelde betekenis. Deze tekst maakte de weg vrij voor de klassieke stelling dat behandeling geoorloofd is, en later verplicht \u2014 en daarmee voor de vraag hoever noodzaak verbodsbepalingen mag opheffen.'},
  {ar:'فَمَنِ اضْطُرَّ غَيْرَ بَاغٍ وَلَا عَادٍ فَلَا إِثْمَ عَلَيْهِ',
  nl:'Wie evenwel gedwongen is, zonder te begeren en zonder te overschrijden, hem treft geen zonde.',
  bron:'Koran 2:173. Het bewijsvers voor <em>darura</em> en tegelijk voor haar begrenzing.',
  g:[['اضْطُرَّ','werd gedwongen (passief, wortel \u0636\u0631\u0631)'],['بَاغٍ','begerig, opzoekend'],['عَادٍ','overschrijdend'],['إِثْمَ','zonde, schuld']],
  w:'De twee ontkenningen zijn de hele beperking: geen opzoeken en geen overschrijden. Daaruit destilleerden de juristen <span class="ar">الضرورة تُقدَّر بقدرها</span> <em>al-darura tuqaddar bi-qadariha</em>. Noodzaak opent een deur en meet tegelijk hoe ver zij opengaat.'}],
 doe:'Neem een concrete casus waarin je een patiënt hebt geadviseerd iets te doen wat hij religieus als problematisch ervoer. Loop de drie toetsvragen van darura langs: werkelijk en actueel, geen alternatief, beperkt tot het nodige. Waar zou het gesprek anders zijn gelopen als je die vragen expliciet had gesteld?'},

t3:{kern:'Wanneer begint het leven dat de wet beschermt?',
 matn:[{ar:'إِنَّ أَحَدَكُمْ يُجْمَعُ خَلْقُهُ فِي بَطْنِ أُمِّهِ أَرْبَعِينَ يَوْمًا نُطْفَةً، ثُمَّ يَكُونُ عَلَقَةً مِثْلَ ذَلِكَ، ثُمَّ يَكُونُ مُضْغَةً مِثْلَ ذَلِكَ، ثُمَّ يُرْسَلُ إِلَيْهِ الْمَلَكُ فَيَنْفُخُ فِيهِ الرُّوحَ',
  nl:'De schepping van ieder van jullie wordt in de buik van zijn moeder veertig dagen samengevoegd als een druppel, daarna is hij evenzolang een aanklevend klompje, daarna evenzolang een kauwsel, waarna de engel naar hem wordt gezonden die de geest in hem blaast.',
  bron:'\u2018Abdallah ibn Mas\u2018ud, bij al-Bukhari en Muslim. Een andere overlevering bij Muslim noemt twee\u00ebnveertig nachten.',
  g:[['يُجْمَعُ خَلْقُهُ','zijn schepping wordt samengebracht'],['نُطْفَةً','druppel, zaad'],['عَلَقَةً','aanklevend klompje'],['مُضْغَةً','kauwsel, klompje'],['يَنْفُخُ','hij blaast in']],
  w:'Dit is de tekst achter alle discussie over de status van de vrucht. Let erop dat de Malikitische school zich niet aan de honderdtwintig dagen bindt: zij verbiedt ingrijpen vanaf de innesteling, omdat het proces vanaf dat moment op leven gericht is. De tekst is dus één ding; de juridische conclusie eruit is iets anders.'}],
 doe:'Reconstrueer welk antwoord je tot nu toe zou hebben gegeven aan een Marokkaanse patiënte die vraagt wat \u201cde islam\u201d over dit onderwerp zegt. Herschrijf dat antwoord met wat je nu weet over het verschil tussen de Hanafitische en de Malikitische positie.'},

t4:{kern:'Wanneer mag je stoppen, en waar ligt de grens naar doden?',
 matn:[{ar:'وَلَا تَقْتُلُوا النَّفْسَ الَّتِي حَرَّمَ اللَّهُ إِلَّا بِالْحَقِّ',
  nl:'En doodt niet de ziel die God onschendbaar heeft verklaard, anders dan met recht.',
  bron:'Koran 17:33 (soera al-Isra\u2019).',
  g:[['لَا تَقْتُلُوا','doodt niet'],['حَرَّمَ','heeft onschendbaar/verboden verklaard'],['بِالْحَقِّ','met recht, rechtmatig']],
  w:'Het verbod is absoluut en kent één uitzonderingsclausule die uitdrukkelijk juridisch is. Daarom scheidt de fiqh het staken van een zinloze behandeling \u2014 nalaten \u2014 scherp van actieve bespoediging \u2014 doden. En daarom kan palliatieve sedatie w\u00e9l. Let hier op het verschil tussen de fiqh-redenering en je eigen richtlijn: het dubbele-effectargument hoort bij het ophogen van opio\u00efden, niet bij sedatie. De KNMG-richtlijn stelt uitdrukkelijk dat palliatieve sedatie normaal medisch handelen is dat het leven niet verkort, bij een refractair symptoom en \u2014 bij continue sedatie \u2014 een levensverwachting van hoogstens twee weken.'}],
 doe:'Schrijf op hoe je zelf het onderscheid maakt tussen behandeling staken en levensbe\u00ebindiging. Vergelijk je eigen formulering met de fiqh-redenering en met het beginsel van het dubbele effect. Waar lopen de drie samen, waar niet?'},

t5:{kern:'Wat is jouw rol als arts in het gesprek over vasten?',
 matn:[{ar:'فَمَن كَانَ مِنكُم مَّرِيضًا أَوْ عَلَىٰ سَفَرٍ فَعِدَّةٌ مِّنْ أَيَّامٍ أُخَرَ ¶ يُرِيدُ اللَّهُ بِكُمُ الْيُسْرَ وَلَا يُرِيدُ بِكُمُ الْعُسْرَ',
  nl:'Wie van jullie ziek is of op reis, een aantal andere dagen dan. \u2014 God wenst het gemakkelijke voor jullie en wenst niet het moeilijke voor jullie.',
  bron:'Twee verzen uit soera al-Baqara, hier naast elkaar gezet: de vrijstelling in 2:184 en de motivering in 2:185. Let op de bewoording \u2014 2:185 opent met <span class="ar">وَمَن كَانَ مَرِيضًا</span>, zonder <span class="ar">مِنكُم</span>.',
  g:[['مَّرِيضًا','ziek'],['سَفَرٍ','reis'],['عِدَّةٌ','een aantal, telling'],['الْيُسْرَ','het gemakkelijke'],['الْعُسْرَ','het moeilijke']],
  w:'De vrijstelling staat niet in een fatwa maar in de wettekst zelf, en de motivering staat er direct achter. Wie dit vers kent, kan aan een aarzelende patiënt uitleggen dat niet-vasten bij ziekte geen tekortkoming is maar de uitvoering van de bepaling. Dat is vaak effectiever dan welk risicocijfer ook.'}],
 doe:'Schrijf een korte tekst van tien regels die je aan een patiënt met slecht ingestelde diabetes zou kunnen meegeven v\u00f3\u00f3r de Ramadan. Gebruik het vers, benoem je eigen rol, en laat de religieuze afweging uitdrukkelijk bij de patiënt.'}
};
