import type { Woord } from './soorten'


/* ============================================================
   WOORDEN — thematische woordenschat, Modern Standaardarabisch
   ------------------------------------------------------------
   a   Arabisch, volledig gevocaliseerd (de app kan de vocalisatie
       naar wens afpellen; opslaan doen we altijd volledig, want
       tekens weghalen kan wel en erbij verzinnen niet)
   t   transcriptie
   n   Nederlands
   th  thema
   b   beeldanker (emoji) — leeg waar geen eerlijk beeld bestaat
   g   grammaticaal geslacht: m of v ('' bij woorden zonder geslacht)
   mv  meervoud, gevocaliseerd (leeg waar niet zinvol)
   d   terzijde over het Marokkaans (Darija) — alleen waar het
       sterk afwijkt; het is een terzijde, geen leerlijn
   s   vanaf welk spoor: 1 = jongste kinderen, 2, 3, 4
   ============================================================ */
export const WOORDEN: Woord[] = [
/* ---------- familie ---------- */
{a:'أَب',t:'ab',n:'vader',th:'familie',b:'👨',g:'m',mv:'آبَاء',s:1,d:'In het Marokkaans hoor je meestal بّا (bba) of الوالد.'},
{a:'أُمّ',t:'umm',n:'moeder',th:'familie',b:'👩',g:'v',mv:'أُمَّهَات',s:1,d:'Marokkaans: مّي (mmi) of الوالدة.'},
{a:'اِبْن',t:'ibn',n:'zoon',th:'familie',b:'👦',g:'m',mv:'أَبْنَاء',s:1},
{a:'بِنْت',t:'bint',n:'dochter, meisje',th:'familie',b:'👧',g:'v',mv:'بَنَات',s:1},
{a:'أَخ',t:'akh',n:'broer',th:'familie',b:'🧑',g:'m',mv:'إِخْوَة',s:1,d:'Marokkaans: خويا (khoya) voor "mijn broer".'},
{a:'أُخْت',t:'ukht',n:'zus',th:'familie',b:'👩',g:'v',mv:'أَخَوَات',s:1},
{a:'جَدّ',t:'jadd',n:'opa',th:'familie',b:'👴',g:'m',mv:'أَجْدَاد',s:1},
{a:'جَدَّة',t:'jadda',n:'oma',th:'familie',b:'👵',g:'v',mv:'جَدَّات',s:1},
{a:'عَمّ',t:'ʿamm',n:'oom van vaderskant',th:'familie',b:'',g:'m',mv:'أَعْمَام',s:2},
{a:'عَمَّة',t:'ʿamma',n:'tante van vaderskant',th:'familie',b:'',g:'v',mv:'عَمَّات',s:2},
{a:'خَال',t:'khāl',n:'oom van moederskant',th:'familie',b:'',g:'m',mv:'أَخْوَال',s:2},
{a:'خَالَة',t:'khāla',n:'tante van moederskant',th:'familie',b:'',g:'v',mv:'خَالَات',s:2},
{a:'زَوْج',t:'zawj',n:'echtgenoot',th:'familie',b:'',g:'m',mv:'أَزْوَاج',s:2},
{a:'زَوْجَة',t:'zawja',n:'echtgenote',th:'familie',b:'',g:'v',mv:'زَوْجَات',s:2},
{a:'وَلَد',t:'walad',n:'jongen, kind',th:'familie',b:'🧒',g:'m',mv:'أَوْلَاد',s:1},
{a:'طِفْل',t:'ṭifl',n:'kind',th:'familie',b:'👶',g:'m',mv:'أَطْفَال',s:1},
{a:'رَجُل',t:'rajul',n:'man',th:'familie',b:'🧔',g:'m',mv:'رِجَال',s:1},
{a:'اِمْرَأَة',t:'imraʾa',n:'vrouw',th:'familie',b:'🧕',g:'v',mv:'نِسَاء',s:2},
{a:'أُسْرَة',t:'usra',n:'gezin',th:'familie',b:'👨‍👩‍👧‍👦',g:'v',mv:'أُسَر',s:2},
{a:'عَائِلَة',t:'ʿāʾila',n:'familie',th:'familie',b:'🏡',g:'v',mv:'عَائِلَات',s:2},
{a:'صَدِيق',t:'ṣadīq',n:'vriend',th:'familie',b:'🤝',g:'m',mv:'أَصْدِقَاء',s:1},
{a:'صَدِيقَة',t:'ṣadīqa',n:'vriendin',th:'familie',b:'',g:'v',mv:'صَدِيقَات',s:2},
{a:'جَار',t:'jār',n:'buurman',th:'familie',b:'',g:'m',mv:'جِيرَان',s:2},
{a:'اِسْم',t:'ism',n:'naam',th:'familie',b:'',g:'m',mv:'أَسْمَاء',s:1},
{a:'ضَيْف',t:'ḍayf',n:'gast',th:'familie',b:'',g:'m',mv:'ضُيُوف',s:2},
{a:'نَاس',t:'nās',n:'mensen',th:'familie',b:'',g:'m',mv:'',s:2},
{a:'شَخْص',t:'shakhṣ',n:'persoon',th:'familie',b:'',g:'m',mv:'أَشْخَاص',s:3},
{a:'أَهْل',t:'ahl',n:'de mensen van, familie',th:'familie',b:'',g:'m',mv:'',s:3},
{a:'حَفِيد',t:'ḥafīd',n:'kleinzoon',th:'familie',b:'',g:'m',mv:'أَحْفَاد',s:3},
{a:'يَتِيم',t:'yatīm',n:'wees',th:'familie',b:'',g:'m',mv:'أَيْتَام',s:3},

/* ---------- lichaam ---------- */
{a:'رَأْس',t:'raʾs',n:'hoofd',th:'lichaam',b:'🗣️',g:'m',mv:'رُؤُوس',s:1},
{a:'شَعْر',t:'shaʿr',n:'haar',th:'lichaam',b:'💇',g:'m',mv:'',s:1},
{a:'وَجْه',t:'wajh',n:'gezicht',th:'lichaam',b:'😐',g:'m',mv:'وُجُوه',s:1},
{a:'عَيْن',t:'ʿayn',n:'oog',th:'lichaam',b:'👁️',g:'v',mv:'عُيُون',s:1},
{a:'أُذُن',t:'udhun',n:'oor',th:'lichaam',b:'👂',g:'v',mv:'آذَان',s:1},
{a:'أَنْف',t:'anf',n:'neus',th:'lichaam',b:'👃',g:'m',mv:'أُنُوف',s:1},
{a:'فَم',t:'fam',n:'mond',th:'lichaam',b:'👄',g:'m',mv:'أَفْوَاه',s:1},
{a:'شَفَة',t:'shafa',n:'lip',th:'lichaam',b:'',g:'v',mv:'شِفَاه',s:2},
{a:'سِنّ',t:'sinn',n:'tand',th:'lichaam',b:'🦷',g:'v',mv:'أَسْنَان',s:1},
{a:'لِسَان',t:'lisān',n:'tong, taal',th:'lichaam',b:'👅',g:'m',mv:'أَلْسِنَة',s:1},
{a:'رَقَبَة',t:'raqaba',n:'nek',th:'lichaam',b:'',g:'v',mv:'رِقَاب',s:2},
{a:'كَتِف',t:'katif',n:'schouder',th:'lichaam',b:'',g:'v',mv:'أَكْتَاف',s:2},
{a:'يَد',t:'yad',n:'hand',th:'lichaam',b:'✋',g:'v',mv:'أَيْدٍ',s:1},
{a:'إِصْبَع',t:'iṣbaʿ',n:'vinger',th:'lichaam',b:'👆',g:'m',mv:'أَصَابِع',s:2},
{a:'ذِرَاع',t:'dhirāʿ',n:'arm',th:'lichaam',b:'💪',g:'v',mv:'أَذْرُع',s:2},
{a:'ظَهْر',t:'ẓahr',n:'rug',th:'lichaam',b:'',g:'m',mv:'ظُهُور',s:2},
{a:'بَطْن',t:'baṭn',n:'buik',th:'lichaam',b:'',g:'m',mv:'بُطُون',s:1},
{a:'قَلْب',t:'qalb',n:'hart',th:'lichaam',b:'❤️',g:'m',mv:'قُلُوب',s:1},
{a:'رِجْل',t:'rijl',n:'been',th:'lichaam',b:'🦵',g:'v',mv:'أَرْجُل',s:1},
{a:'قَدَم',t:'qadam',n:'voet',th:'lichaam',b:'🦶',g:'v',mv:'أَقْدَام',s:2},
{a:'رُكْبَة',t:'rukba',n:'knie',th:'lichaam',b:'',g:'v',mv:'رُكَب',s:2},
{a:'دَم',t:'dam',n:'bloed',th:'lichaam',b:'🩸',g:'m',mv:'دِمَاء',s:2},
{a:'عَظْم',t:'ʿaẓm',n:'bot',th:'lichaam',b:'🦴',g:'m',mv:'عِظَام',s:2},
{a:'جِلْد',t:'jild',n:'huid',th:'lichaam',b:'',g:'m',mv:'جُلُود',s:3},
{a:'عَقْل',t:'ʿaql',n:'verstand',th:'lichaam',b:'🧠',g:'m',mv:'عُقُول',s:3},
{a:'صَوْت',t:'ṣawt',n:'stem, geluid',th:'lichaam',b:'🔊',g:'m',mv:'أَصْوَات',s:2},
{a:'جِسْم',t:'jism',n:'lichaam',th:'lichaam',b:'',g:'m',mv:'أَجْسَام',s:2},
{a:'صِحَّة',t:'ṣiḥḥa',n:'gezondheid',th:'lichaam',b:'',g:'v',mv:'',s:2},
{a:'مَرَض',t:'maraḍ',n:'ziekte',th:'lichaam',b:'🤒',g:'m',mv:'أَمْرَاض',s:2},
{a:'أَلَم',t:'alam',n:'pijn',th:'lichaam',b:'',g:'m',mv:'آلَام',s:3},

/* ---------- eten ---------- */
{a:'خُبْز',t:'khubz',n:'brood',th:'eten',b:'🍞',g:'m',mv:'',s:1},
{a:'مَاء',t:'māʾ',n:'water',th:'eten',b:'💧',g:'m',mv:'مِيَاه',s:1},
{a:'حَلِيب',t:'ḥalīb',n:'melk',th:'eten',b:'🥛',g:'m',mv:'',s:1},
{a:'شَاي',t:'shāy',n:'thee',th:'eten',b:'🍵',g:'m',mv:'',s:1,d:'In Marokko is أتاي (atay) het gewone woord voor muntthee.'},
{a:'قَهْوَة',t:'qahwa',n:'koffie',th:'eten',b:'☕',g:'v',mv:'',s:1},
{a:'عَصِير',t:'ʿaṣīr',n:'sap',th:'eten',b:'🧃',g:'m',mv:'عَصَائِر',s:1},
{a:'سُكَّر',t:'sukkar',n:'suiker',th:'eten',b:'🍬',g:'m',mv:'',s:1},
{a:'مِلْح',t:'milḥ',n:'zout',th:'eten',b:'🧂',g:'m',mv:'',s:1},
{a:'زَيْت',t:'zayt',n:'olie',th:'eten',b:'🫒',g:'m',mv:'زُيُوت',s:2},
{a:'زَيْتُون',t:'zaytūn',n:'olijven',th:'eten',b:'🫒',g:'m',mv:'',s:2},
{a:'أَرُزّ',t:'aruzz',n:'rijst',th:'eten',b:'🍚',g:'m',mv:'',s:1},
{a:'لَحْم',t:'laḥm',n:'vlees',th:'eten',b:'🥩',g:'m',mv:'لُحُوم',s:1},
{a:'دَجَاج',t:'dajāj',n:'kip (als vlees)',th:'eten',b:'🍗',g:'m',mv:'',s:1},
{a:'سَمَك',t:'samak',n:'vis (als voedsel)',th:'eten',b:'🐟',g:'m',mv:'أَسْمَاك',s:1},
{a:'بَيْضَة',t:'bayḍa',n:'ei',th:'eten',b:'🥚',g:'v',mv:'بَيْض',s:1},
{a:'جُبْن',t:'jubn',n:'kaas',th:'eten',b:'🧀',g:'m',mv:'',s:1},
{a:'زُبْدَة',t:'zubda',n:'boter',th:'eten',b:'🧈',g:'v',mv:'',s:2},
{a:'عَسَل',t:'ʿasal',n:'honing',th:'eten',b:'🍯',g:'m',mv:'',s:1},
{a:'تَمْر',t:'tamr',n:'dadels',th:'eten',b:'🌴',g:'m',mv:'تُمُور',s:1},
{a:'تُفَّاحَة',t:'tuffāḥa',n:'appel',th:'eten',b:'🍎',g:'v',mv:'تُفَّاح',s:1},
{a:'مَوْزَة',t:'mawza',n:'banaan',th:'eten',b:'🍌',g:'v',mv:'مَوْز',s:1},
{a:'بُرْتُقَالَة',t:'burtuqāla',n:'sinaasappel',th:'eten',b:'🍊',g:'v',mv:'بُرْتُقَال',s:1},
{a:'عِنَب',t:'ʿinab',n:'druiven',th:'eten',b:'🍇',g:'m',mv:'',s:1},
{a:'بَطِّيخ',t:'baṭṭīkh',n:'meloen',th:'eten',b:'🍉',g:'m',mv:'',s:2},
{a:'لَيْمُون',t:'laymūn',n:'citroen',th:'eten',b:'🍋',g:'m',mv:'',s:2},
{a:'خُضَار',t:'khuḍār',n:'groente',th:'eten',b:'🥬',g:'m',mv:'',s:1},
{a:'طَمَاطِم',t:'ṭamāṭim',n:'tomaten',th:'eten',b:'🍅',g:'v',mv:'',s:1,d:'Marokkaans: ماطيشة (maṭīsha).'},
{a:'بَطَاطِس',t:'baṭāṭis',n:'aardappelen',th:'eten',b:'🥔',g:'v',mv:'',s:1},
{a:'جَزَر',t:'jazar',n:'wortels',th:'eten',b:'🥕',g:'m',mv:'',s:1},
{a:'بَصَل',t:'baṣal',n:'uien',th:'eten',b:'🧅',g:'m',mv:'',s:2},
{a:'ثُوم',t:'thūm',n:'knoflook',th:'eten',b:'🧄',g:'m',mv:'',s:2},
{a:'خِيَار',t:'khiyār',n:'komkommer',th:'eten',b:'🥒',g:'m',mv:'',s:2},
{a:'سَلَطَة',t:'salaṭa',n:'salade',th:'eten',b:'🥗',g:'v',mv:'',s:1},
{a:'حَسَاء',t:'ḥasāʾ',n:'soep',th:'eten',b:'🍲',g:'m',mv:'',s:2,d:'In Marokko heet de bekendste soep حريرة (ḥarīra).'},
{a:'طَعَام',t:'ṭaʿām',n:'eten, voedsel',th:'eten',b:'🍽️',g:'m',mv:'أَطْعِمَة',s:1},
{a:'فَطُور',t:'faṭūr',n:'ontbijt',th:'eten',b:'🥣',g:'m',mv:'',s:2},
{a:'غَدَاء',t:'ghadāʾ',n:'lunch',th:'eten',b:'',g:'m',mv:'',s:2},
{a:'عَشَاء',t:'ʿashāʾ',n:'avondeten',th:'eten',b:'',g:'m',mv:'',s:2},
{a:'مَطْعَم',t:'maṭʿam',n:'restaurant',th:'eten',b:'🍴',g:'m',mv:'مَطَاعِم',s:2},
{a:'حَلْوَى',t:'ḥalwā',n:'zoetigheid',th:'eten',b:'🍰',g:'v',mv:'',s:1},

/* ---------- huis ---------- */
{a:'بَيْت',t:'bayt',n:'huis',th:'huis',b:'🏠',g:'m',mv:'بُيُوت',s:1},
{a:'دَار',t:'dār',n:'woning',th:'huis',b:'🏡',g:'v',mv:'دُور',s:2,d:'In het Marokkaans is دار het gewone woord voor huis; بيت betekent daar vaak "kamer".'},
{a:'غُرْفَة',t:'ghurfa',n:'kamer',th:'huis',b:'🛋️',g:'v',mv:'غُرَف',s:1},
{a:'بَاب',t:'bāb',n:'deur',th:'huis',b:'🚪',g:'m',mv:'أَبْوَاب',s:1},
{a:'نَافِذَة',t:'nāfidha',n:'raam',th:'huis',b:'🪟',g:'v',mv:'نَوَافِذ',s:1},
{a:'جِدَار',t:'jidār',n:'muur',th:'huis',b:'🧱',g:'m',mv:'جُدْرَان',s:2},
{a:'سَقْف',t:'saqf',n:'plafond, dak',th:'huis',b:'',g:'m',mv:'سُقُوف',s:2},
{a:'مِفْتَاح',t:'miftāḥ',n:'sleutel',th:'huis',b:'🔑',g:'m',mv:'مَفَاتِيح',s:1},
{a:'كُرْسِيّ',t:'kursī',n:'stoel',th:'huis',b:'🪑',g:'m',mv:'كَرَاسِي',s:1},
{a:'طَاوِلَة',t:'ṭāwila',n:'tafel',th:'huis',b:'',g:'v',mv:'طَاوِلَات',s:1},
{a:'سَرِير',t:'sarīr',n:'bed',th:'huis',b:'🛏️',g:'m',mv:'أَسِرَّة',s:1},
{a:'مَطْبَخ',t:'maṭbakh',n:'keuken',th:'huis',b:'🍳',g:'m',mv:'مَطَابِخ',s:1},
{a:'حَمَّام',t:'ḥammām',n:'badkamer',th:'huis',b:'🛁',g:'m',mv:'حَمَّامَات',s:1},
{a:'سُلَّم',t:'sullam',n:'trap',th:'huis',b:'🪜',g:'m',mv:'سَلَالِم',s:2},
{a:'مِرْآة',t:'mirʾāh',n:'spiegel',th:'huis',b:'🪞',g:'v',mv:'مَرَايَا',s:2},
{a:'سَجَّادَة',t:'sajjāda',n:'tapijt',th:'huis',b:'🧶',g:'v',mv:'سَجَّاد',s:2},
{a:'مِصْبَاح',t:'miṣbāḥ',n:'lamp',th:'huis',b:'💡',g:'m',mv:'مَصَابِيح',s:2},
{a:'تِلْفَاز',t:'tilfāz',n:'televisie',th:'huis',b:'📺',g:'m',mv:'',s:1},
{a:'هَاتِف',t:'hātif',n:'telefoon',th:'huis',b:'📱',g:'m',mv:'هَوَاتِف',s:1},
{a:'كُوب',t:'kūb',n:'beker',th:'huis',b:'🥤',g:'m',mv:'أَكْوَاب',s:1},
{a:'صَحْن',t:'ṣaḥn',n:'bord',th:'huis',b:'🍽️',g:'m',mv:'صُحُون',s:1},
{a:'مِلْعَقَة',t:'milʿaqa',n:'lepel',th:'huis',b:'🥄',g:'v',mv:'مَلَاعِق',s:1},
{a:'سِكِّين',t:'sikkīn',n:'mes',th:'huis',b:'🔪',g:'m',mv:'سَكَاكِين',s:2},
{a:'شَوْكَة',t:'shawka',n:'vork',th:'huis',b:'🍴',g:'v',mv:'شِوَك',s:2},
{a:'ثَلَّاجَة',t:'thallāja',n:'koelkast',th:'huis',b:'🧊',g:'v',mv:'ثَلَّاجَات',s:2},
{a:'حَدِيقَة',t:'ḥadīqa',n:'tuin',th:'huis',b:'🌳',g:'v',mv:'حَدَائِق',s:1},
{a:'مِنْشَفَة',t:'minshafa',n:'handdoek',th:'huis',b:'🧻',g:'v',mv:'مَنَاشِف',s:3},
{a:'صَابُون',t:'ṣābūn',n:'zeep',th:'huis',b:'🧼',g:'m',mv:'',s:2},
{a:'خِزَانَة',t:'khizāna',n:'kast',th:'huis',b:'🗄️',g:'v',mv:'خَزَائِن',s:2},
{a:'سَاعَة',t:'sāʿa',n:'klok, uur',th:'huis',b:'🕐',g:'v',mv:'سَاعَات',s:1},

/* ---------- school ---------- */
{a:'مَدْرَسَة',t:'madrasa',n:'school',th:'school',b:'🏫',g:'v',mv:'مَدَارِس',s:1},
{a:'كِتَاب',t:'kitāb',n:'boek',th:'school',b:'📕',g:'m',mv:'كُتُب',s:1},
{a:'قَلَم',t:'qalam',n:'pen',th:'school',b:'🖊️',g:'m',mv:'أَقْلَام',s:1},
{a:'دَفْتَر',t:'daftar',n:'schrift',th:'school',b:'📓',g:'m',mv:'دَفَاتِر',s:1},
{a:'وَرَقَة',t:'waraqa',n:'blad papier',th:'school',b:'📄',g:'v',mv:'أَوْرَاق',s:1},
{a:'حَقِيبَة',t:'ḥaqība',n:'tas',th:'school',b:'🎒',g:'v',mv:'حَقَائِب',s:1},
{a:'مُعَلِّم',t:'muʿallim',n:'leraar',th:'school',b:'👨‍🏫',g:'m',mv:'مُعَلِّمُونَ',s:1},
{a:'مُعَلِّمَة',t:'muʿallima',n:'lerares',th:'school',b:'👩‍🏫',g:'v',mv:'مُعَلِّمَات',s:1},
{a:'طَالِب',t:'ṭālib',n:'leerling, student',th:'school',b:'🧑‍🎓',g:'m',mv:'طُلَّاب',s:1},
{a:'طَالِبَة',t:'ṭāliba',n:'leerlinge',th:'school',b:'👩‍🎓',g:'v',mv:'طَالِبَات',s:1},
{a:'دَرْس',t:'dars',n:'les',th:'school',b:'',g:'m',mv:'دُرُوس',s:1},
{a:'صَفّ',t:'ṣaff',n:'klas, rij',th:'school',b:'',g:'m',mv:'صُفُوف',s:1},
{a:'سَبُّورَة',t:'sabbūra',n:'schoolbord',th:'school',b:'',g:'v',mv:'سَبُّورَات',s:2},
{a:'اِمْتِحَان',t:'imtiḥān',n:'toets, examen',th:'school',b:'📝',g:'m',mv:'اِمْتِحَانَات',s:2},
{a:'سُؤَال',t:'suʾāl',n:'vraag',th:'school',b:'❓',g:'m',mv:'أَسْئِلَة',s:1},
{a:'جَوَاب',t:'jawāb',n:'antwoord',th:'school',b:'',g:'m',mv:'أَجْوِبَة',s:1},
{a:'كَلِمَة',t:'kalima',n:'woord',th:'school',b:'',g:'v',mv:'كَلِمَات',s:1},
{a:'جُمْلَة',t:'jumla',n:'zin',th:'school',b:'',g:'v',mv:'جُمَل',s:2},
{a:'حَرْف',t:'ḥarf',n:'letter',th:'school',b:'🔤',g:'m',mv:'حُرُوف',s:1},
{a:'لُغَة',t:'lugha',n:'taal',th:'school',b:'🗣️',g:'v',mv:'لُغَات',s:1},
{a:'رَقْم',t:'raqm',n:'nummer',th:'school',b:'🔢',g:'m',mv:'أَرْقَام',s:1},
{a:'عِلْم',t:'ʿilm',n:'kennis, wetenschap',th:'school',b:'',g:'m',mv:'عُلُوم',s:2},
{a:'تَارِيخ',t:'tārīkh',n:'geschiedenis, datum',th:'school',b:'',g:'m',mv:'تَوَارِيخ',s:3},
{a:'رِيَاضِيَّات',t:'riyāḍiyyāt',n:'wiskunde',th:'school',b:'➗',g:'v',mv:'',s:2},
{a:'مَكْتَبَة',t:'maktaba',n:'bibliotheek',th:'school',b:'📚',g:'v',mv:'مَكْتَبَات',s:2},
{a:'وَاجِب',t:'wājib',n:'huiswerk, plicht',th:'school',b:'',g:'m',mv:'وَاجِبَات',s:2},
{a:'عُطْلَة',t:'ʿuṭla',n:'vakantie',th:'school',b:'🏖️',g:'v',mv:'عُطَل',s:2},
{a:'مِمْحَاة',t:'mimḥāh',n:'gum',th:'school',b:'',g:'v',mv:'مَمَاحٍ',s:2},
{a:'مِسْطَرَة',t:'misṭara',n:'liniaal',th:'school',b:'📏',g:'v',mv:'مَسَاطِر',s:2},
{a:'قِصَّة',t:'qiṣṣa',n:'verhaal',th:'school',b:'📖',g:'v',mv:'قِصَص',s:1},

/* ---------- kleuren ---------- */
{a:'لَوْن',t:'lawn',n:'kleur',th:'kleuren',b:'🎨',g:'m',mv:'أَلْوَان',s:1},
{a:'أَحْمَر',t:'aḥmar',n:'rood',th:'kleuren',b:'🔴',g:'m',mv:'حُمْر',s:1},
{a:'أَزْرَق',t:'azraq',n:'blauw',th:'kleuren',b:'🔵',g:'m',mv:'زُرْق',s:1},
{a:'أَخْضَر',t:'akhḍar',n:'groen',th:'kleuren',b:'🟢',g:'m',mv:'خُضْر',s:1},
{a:'أَصْفَر',t:'aṣfar',n:'geel',th:'kleuren',b:'🟡',g:'m',mv:'صُفْر',s:1},
{a:'أَبْيَض',t:'abyaḍ',n:'wit',th:'kleuren',b:'⚪',g:'m',mv:'بِيض',s:1},
{a:'أَسْوَد',t:'aswad',n:'zwart',th:'kleuren',b:'⚫',g:'m',mv:'سُود',s:1},
{a:'بُنِّيّ',t:'bunnī',n:'bruin',th:'kleuren',b:'🟤',g:'m',mv:'',s:1},
{a:'رَمَادِيّ',t:'ramādī',n:'grijs',th:'kleuren',b:'',g:'m',mv:'',s:2},
{a:'بُرْتُقَالِيّ',t:'burtuqālī',n:'oranje',th:'kleuren',b:'🟠',g:'m',mv:'',s:1},
{a:'وَرْدِيّ',t:'wardī',n:'roze',th:'kleuren',b:'🌸',g:'m',mv:'',s:1},
{a:'بَنَفْسَجِيّ',t:'banafsajī',n:'paars',th:'kleuren',b:'🟣',g:'m',mv:'',s:2},
{a:'ذَهَبِيّ',t:'dhahabī',n:'goudkleurig',th:'kleuren',b:'🥇',g:'m',mv:'',s:3},
{a:'فِضِّيّ',t:'fiḍḍī',n:'zilverkleurig',th:'kleuren',b:'🥈',g:'m',mv:'',s:3},

/* ---------- getallen ---------- */
{a:'صِفْر',t:'ṣifr',n:'nul',th:'getallen',b:'0️⃣',g:'m',mv:'',s:1},
{a:'وَاحِد',t:'wāḥid',n:'één',th:'getallen',b:'1️⃣',g:'m',mv:'',s:1},
{a:'اِثْنَان',t:'ithnān',n:'twee',th:'getallen',b:'2️⃣',g:'m',mv:'',s:1},
{a:'ثَلَاثَة',t:'thalātha',n:'drie',th:'getallen',b:'3️⃣',g:'v',mv:'',s:1},
{a:'أَرْبَعَة',t:'arbaʿa',n:'vier',th:'getallen',b:'4️⃣',g:'v',mv:'',s:1},
{a:'خَمْسَة',t:'khamsa',n:'vijf',th:'getallen',b:'5️⃣',g:'v',mv:'',s:1},
{a:'سِتَّة',t:'sitta',n:'zes',th:'getallen',b:'6️⃣',g:'v',mv:'',s:1},
{a:'سَبْعَة',t:'sabʿa',n:'zeven',th:'getallen',b:'7️⃣',g:'v',mv:'',s:1},
{a:'ثَمَانِيَة',t:'thamāniya',n:'acht',th:'getallen',b:'8️⃣',g:'v',mv:'',s:1},
{a:'تِسْعَة',t:'tisʿa',n:'negen',th:'getallen',b:'9️⃣',g:'v',mv:'',s:1},
{a:'عَشَرَة',t:'ʿashara',n:'tien',th:'getallen',b:'🔟',g:'v',mv:'',s:1},
{a:'أَحَدَ عَشَرَ',t:'aḥada ʿashara',n:'elf',th:'getallen',b:'',g:'m',mv:'',s:2},
{a:'اِثْنَا عَشَرَ',t:'ithnā ʿashara',n:'twaalf',th:'getallen',b:'',g:'m',mv:'',s:2},
{a:'عِشْرُونَ',t:'ʿishrūna',n:'twintig',th:'getallen',b:'',g:'m',mv:'',s:2},
{a:'ثَلَاثُونَ',t:'thalāthūna',n:'dertig',th:'getallen',b:'',g:'m',mv:'',s:2},
{a:'أَرْبَعُونَ',t:'arbaʿūna',n:'veertig',th:'getallen',b:'',g:'m',mv:'',s:2},
{a:'خَمْسُونَ',t:'khamsūna',n:'vijftig',th:'getallen',b:'',g:'m',mv:'',s:2},
{a:'مِائَة',t:'miʾa',n:'honderd',th:'getallen',b:'💯',g:'v',mv:'مِئَات',s:2},
{a:'أَلْف',t:'alf',n:'duizend',th:'getallen',b:'',g:'m',mv:'آلَاف',s:2},
{a:'أَوَّل',t:'awwal',n:'eerste',th:'getallen',b:'🥇',g:'m',mv:'',s:2},
{a:'ثَانٍ',t:'thānin',n:'tweede',th:'getallen',b:'🥈',g:'m',mv:'',s:3},
{a:'ثَالِث',t:'thālith',n:'derde',th:'getallen',b:'🥉',g:'m',mv:'',s:3},
{a:'نِصْف',t:'niṣf',n:'helft',th:'getallen',b:'',g:'m',mv:'أَنْصَاف',s:2},
{a:'رُبْع',t:'rubʿ',n:'kwart',th:'getallen',b:'',g:'m',mv:'أَرْبَاع',s:3},

/* ---------- dieren ---------- */
{a:'حَيَوَان',t:'ḥayawān',n:'dier',th:'dieren',b:'🐾',g:'m',mv:'حَيَوَانَات',s:1},
{a:'قِطّ',t:'qiṭṭ',n:'kat',th:'dieren',b:'🐈',g:'m',mv:'قِطَط',s:1,d:'Marokkaans: مش (mešš).'},
{a:'كَلْب',t:'kalb',n:'hond',th:'dieren',b:'🐕',g:'m',mv:'كِلَاب',s:1},
{a:'حِصَان',t:'ḥiṣān',n:'paard',th:'dieren',b:'🐎',g:'m',mv:'أَحْصِنَة',s:1},
{a:'جَمَل',t:'jamal',n:'kameel',th:'dieren',b:'🐪',g:'m',mv:'جِمَال',s:1},
{a:'بَقَرَة',t:'baqara',n:'koe',th:'dieren',b:'🐄',g:'v',mv:'بَقَر',s:1},
{a:'خَرُوف',t:'kharūf',n:'schaap',th:'dieren',b:'🐑',g:'m',mv:'خِرَاف',s:1},
{a:'مَاعِز',t:'māʿiz',n:'geit',th:'dieren',b:'🐐',g:'m',mv:'',s:2},
{a:'دَجَاجَة',t:'dajāja',n:'kip',th:'dieren',b:'🐔',g:'v',mv:'دَجَاج',s:1},
{a:'دِيك',t:'dīk',n:'haan',th:'dieren',b:'🐓',g:'m',mv:'دِيَكَة',s:2},
{a:'عُصْفُور',t:'ʿuṣfūr',n:'musje, vogeltje',th:'dieren',b:'🐦',g:'m',mv:'عَصَافِير',s:1},
{a:'طَائِر',t:'ṭāʾir',n:'vogel',th:'dieren',b:'🕊️',g:'m',mv:'طُيُور',s:1},
{a:'سَمَكَة',t:'samaka',n:'vis',th:'dieren',b:'🐠',g:'v',mv:'أَسْمَاك',s:1},
{a:'أَسَد',t:'asad',n:'leeuw',th:'dieren',b:'🦁',g:'m',mv:'أُسُود',s:1},
{a:'فِيل',t:'fīl',n:'olifant',th:'dieren',b:'🐘',g:'m',mv:'أَفْيَال',s:1},
{a:'قِرْد',t:'qird',n:'aap',th:'dieren',b:'🐒',g:'m',mv:'قُرُود',s:1},
{a:'ذِئْب',t:'dhiʾb',n:'wolf',th:'dieren',b:'🐺',g:'m',mv:'ذِئَاب',s:2},
{a:'ثَعْلَب',t:'thaʿlab',n:'vos',th:'dieren',b:'🦊',g:'m',mv:'ثَعَالِب',s:2},
{a:'أَرْنَب',t:'arnab',n:'konijn',th:'dieren',b:'🐇',g:'m',mv:'أَرَانِب',s:1},
{a:'فَأْر',t:'faʾr',n:'muis',th:'dieren',b:'🐁',g:'m',mv:'فِئْرَان',s:1},
{a:'نَحْلَة',t:'naḥla',n:'bij',th:'dieren',b:'🐝',g:'v',mv:'نَحْل',s:1},
{a:'نَمْلَة',t:'namla',n:'mier',th:'dieren',b:'🐜',g:'v',mv:'نَمْل',s:1},
{a:'فَرَاشَة',t:'farāsha',n:'vlinder',th:'dieren',b:'🦋',g:'v',mv:'فَرَاشَات',s:1},
{a:'ثُعْبَان',t:'thuʿbān',n:'slang',th:'dieren',b:'🐍',g:'m',mv:'ثَعَابِين',s:2},
{a:'سُلَحْفَاة',t:'sulaḥfāh',n:'schildpad',th:'dieren',b:'🐢',g:'v',mv:'سَلَاحِف',s:2},
{a:'دُبّ',t:'dubb',n:'beer',th:'dieren',b:'🐻',g:'m',mv:'دِبَبَة',s:1},
{a:'بَطَّة',t:'baṭṭa',n:'eend',th:'dieren',b:'🦆',g:'v',mv:'بَطّ',s:1},

/* ---------- tijd ---------- */
{a:'وَقْت',t:'waqt',n:'tijd',th:'tijd',b:'⏳',g:'m',mv:'أَوْقَات',s:1},
{a:'يَوْم',t:'yawm',n:'dag',th:'tijd',b:'📅',g:'m',mv:'أَيَّام',s:1},
{a:'لَيْلَة',t:'layla',n:'nacht',th:'tijd',b:'🌙',g:'v',mv:'لَيَالٍ',s:1},
{a:'صَبَاح',t:'ṣabāḥ',n:'ochtend',th:'tijd',b:'🌅',g:'m',mv:'',s:1},
{a:'ظُهْر',t:'ẓuhr',n:'middag',th:'tijd',b:'🌞',g:'m',mv:'',s:2},
{a:'مَسَاء',t:'masāʾ',n:'avond',th:'tijd',b:'🌆',g:'m',mv:'',s:1},
{a:'أُسْبُوع',t:'usbūʿ',n:'week',th:'tijd',b:'',g:'m',mv:'أَسَابِيع',s:1},
{a:'شَهْر',t:'shahr',n:'maand',th:'tijd',b:'🗓️',g:'m',mv:'شُهُور',s:1},
{a:'سَنَة',t:'sana',n:'jaar',th:'tijd',b:'',g:'v',mv:'سَنَوَات',s:1},
{a:'دَقِيقَة',t:'daqīqa',n:'minuut',th:'tijd',b:'',g:'v',mv:'دَقَائِق',s:2},
{a:'ثَانِيَة',t:'thāniya',n:'seconde',th:'tijd',b:'',g:'v',mv:'ثَوَانٍ',s:3},
{a:'الْيَوْم',t:'al-yawm',n:'vandaag',th:'tijd',b:'',g:'m',mv:'',s:1},
{a:'غَدًا',t:'ghadan',n:'morgen',th:'tijd',b:'',g:'',mv:'',s:1},
{a:'أَمْسِ',t:'ams',n:'gisteren',th:'tijd',b:'',g:'',mv:'',s:1},
{a:'الْآنَ',t:'al-āna',n:'nu',th:'tijd',b:'',g:'',mv:'',s:1},
{a:'دَائِمًا',t:'dāʾiman',n:'altijd',th:'tijd',b:'',g:'',mv:'',s:2},
{a:'أَحْيَانًا',t:'aḥyānan',n:'soms',th:'tijd',b:'',g:'',mv:'',s:2},
{a:'أَبَدًا',t:'abadan',n:'nooit',th:'tijd',b:'',g:'',mv:'',s:2},
{a:'مُبَكِّرًا',t:'mubakkiran',n:'vroeg',th:'tijd',b:'',g:'',mv:'',s:3},
{a:'مُتَأَخِّرًا',t:'mutaʾakhkhiran',n:'laat',th:'tijd',b:'',g:'',mv:'',s:3},
{a:'الْأَحَد',t:'al-aḥad',n:'zondag',th:'tijd',b:'',g:'m',mv:'',s:1},
{a:'الْاِثْنَيْن',t:'al-ithnayn',n:'maandag',th:'tijd',b:'',g:'m',mv:'',s:1},
{a:'الثُّلَاثَاء',t:'ath-thulāthāʾ',n:'dinsdag',th:'tijd',b:'',g:'m',mv:'',s:1},
{a:'الْأَرْبِعَاء',t:'al-arbiʿāʾ',n:'woensdag',th:'tijd',b:'',g:'m',mv:'',s:1},
{a:'الْخَمِيس',t:'al-khamīs',n:'donderdag',th:'tijd',b:'',g:'m',mv:'',s:1},
{a:'الْجُمُعَة',t:'al-jumuʿa',n:'vrijdag',th:'tijd',b:'🕌',g:'v',mv:'',s:1},
{a:'السَّبْت',t:'as-sabt',n:'zaterdag',th:'tijd',b:'',g:'m',mv:'',s:1},
{a:'رَمَضَان',t:'ramaḍān',n:'ramadan',th:'tijd',b:'🌙',g:'m',mv:'',s:1},
{a:'عِيد',t:'ʿīd',n:'feest',th:'tijd',b:'🎉',g:'m',mv:'أَعْيَاد',s:1},

/* ---------- gevoelens & eigenschappen ---------- */
{a:'سَعِيد',t:'saʿīd',n:'blij',th:'gevoelens',b:'😊',g:'m',mv:'سُعَدَاء',s:1},
{a:'حَزِين',t:'ḥazīn',n:'verdrietig',th:'gevoelens',b:'😢',g:'m',mv:'حِزَان',s:1},
{a:'غَاضِب',t:'ghāḍib',n:'boos',th:'gevoelens',b:'😠',g:'m',mv:'',s:1},
{a:'خَائِف',t:'khāʾif',n:'bang',th:'gevoelens',b:'😨',g:'m',mv:'',s:1},
{a:'مُتْعَب',t:'mutʿab',n:'moe',th:'gevoelens',b:'😴',g:'m',mv:'',s:1},
{a:'جَائِع',t:'jāʾiʿ',n:'hongerig',th:'gevoelens',b:'😋',g:'m',mv:'',s:1},
{a:'عَطْشَان',t:'ʿaṭshān',n:'dorstig',th:'gevoelens',b:'🥤',g:'m',mv:'',s:1},
{a:'مَرِيض',t:'marīḍ',n:'ziek',th:'gevoelens',b:'🤒',g:'m',mv:'مَرْضَى',s:1},
{a:'قَوِيّ',t:'qawī',n:'sterk',th:'gevoelens',b:'💪',g:'m',mv:'أَقْوِيَاء',s:1},
{a:'ضَعِيف',t:'ḍaʿīf',n:'zwak',th:'gevoelens',b:'',g:'m',mv:'ضُعَفَاء',s:2},
{a:'كَبِير',t:'kabīr',n:'groot',th:'gevoelens',b:'',g:'m',mv:'كِبَار',s:1},
{a:'صَغِير',t:'ṣaghīr',n:'klein',th:'gevoelens',b:'',g:'m',mv:'صِغَار',s:1},
{a:'طَوِيل',t:'ṭawīl',n:'lang',th:'gevoelens',b:'',g:'m',mv:'طِوَال',s:1},
{a:'قَصِير',t:'qaṣīr',n:'kort',th:'gevoelens',b:'',g:'m',mv:'قِصَار',s:1},
{a:'جَمِيل',t:'jamīl',n:'mooi',th:'gevoelens',b:'✨',g:'m',mv:'',s:1},
{a:'جَدِيد',t:'jadīd',n:'nieuw',th:'gevoelens',b:'',g:'m',mv:'جُدُد',s:1},
{a:'قَدِيم',t:'qadīm',n:'oud (van zaken)',th:'gevoelens',b:'',g:'m',mv:'قُدَمَاء',s:2},
{a:'سَرِيع',t:'sarīʿ',n:'snel',th:'gevoelens',b:'⚡',g:'m',mv:'سِرَاع',s:1},
{a:'بَطِيء',t:'baṭīʾ',n:'langzaam',th:'gevoelens',b:'🐌',g:'m',mv:'',s:2},
{a:'سَهْل',t:'sahl',n:'makkelijk',th:'gevoelens',b:'',g:'m',mv:'',s:1},
{a:'صَعْب',t:'ṣaʿb',n:'moeilijk',th:'gevoelens',b:'',g:'m',mv:'صِعَاب',s:1},
{a:'مَشْغُول',t:'mashghūl',n:'druk bezig',th:'gevoelens',b:'',g:'m',mv:'',s:3},
{a:'هَادِئ',t:'hādiʾ',n:'rustig',th:'gevoelens',b:'',g:'m',mv:'',s:2},
{a:'نَظِيف',t:'naẓīf',n:'schoon',th:'gevoelens',b:'🧼',g:'m',mv:'نِظَاف',s:1},
{a:'وَسِخ',t:'wasikh',n:'vuil',th:'gevoelens',b:'',g:'m',mv:'',s:2},
{a:'حُبّ',t:'ḥubb',n:'liefde',th:'gevoelens',b:'❤️',g:'m',mv:'',s:2},
{a:'فَرَح',t:'faraḥ',n:'vreugde',th:'gevoelens',b:'🎈',g:'m',mv:'أَفْرَاح',s:2},
{a:'خَوْف',t:'khawf',n:'angst',th:'gevoelens',b:'',g:'m',mv:'',s:3},
{a:'غَضَب',t:'ghaḍab',n:'woede',th:'gevoelens',b:'',g:'m',mv:'',s:3},
{a:'صَبْر',t:'ṣabr',n:'geduld',th:'gevoelens',b:'',g:'m',mv:'',s:3},

/* ---------- werkwoorden ---------- */
{a:'ذَهَبَ',t:'dhahaba',n:'hij ging',th:'werkwoorden',b:'🚶',g:'',mv:'يَذْهَبُ',s:2},
{a:'جَاءَ',t:'jāʾa',n:'hij kwam',th:'werkwoorden',b:'',g:'',mv:'يَجِيءُ',s:2},
{a:'أَكَلَ',t:'akala',n:'hij at',th:'werkwoorden',b:'🍽️',g:'',mv:'يَأْكُلُ',s:1},
{a:'شَرِبَ',t:'shariba',n:'hij dronk',th:'werkwoorden',b:'🥛',g:'',mv:'يَشْرَبُ',s:1},
{a:'كَتَبَ',t:'kataba',n:'hij schreef',th:'werkwoorden',b:'✍️',g:'',mv:'يَكْتُبُ',s:1},
{a:'قَرَأَ',t:'qaraʾa',n:'hij las',th:'werkwoorden',b:'📖',g:'',mv:'يَقْرَأُ',s:1},
{a:'دَرَسَ',t:'darasa',n:'hij studeerde',th:'werkwoorden',b:'',g:'',mv:'يَدْرُسُ',s:2},
{a:'لَعِبَ',t:'laʿiba',n:'hij speelde',th:'werkwoorden',b:'⚽',g:'',mv:'يَلْعَبُ',s:1},
{a:'نَامَ',t:'nāma',n:'hij sliep',th:'werkwoorden',b:'😴',g:'',mv:'يَنَامُ',s:1},
{a:'جَلَسَ',t:'jalasa',n:'hij zat',th:'werkwoorden',b:'',g:'',mv:'يَجْلِسُ',s:2},
{a:'وَقَفَ',t:'waqafa',n:'hij stond',th:'werkwoorden',b:'',g:'',mv:'يَقِفُ',s:3},
{a:'مَشَى',t:'mashā',n:'hij liep',th:'werkwoorden',b:'',g:'',mv:'يَمْشِي',s:2},
{a:'رَكَضَ',t:'rakaḍa',n:'hij rende',th:'werkwoorden',b:'🏃',g:'',mv:'يَرْكُضُ',s:2},
{a:'فَتَحَ',t:'fataḥa',n:'hij opende',th:'werkwoorden',b:'',g:'',mv:'يَفْتَحُ',s:1},
{a:'أَغْلَقَ',t:'aghlaqa',n:'hij sloot',th:'werkwoorden',b:'',g:'',mv:'يُغْلِقُ',s:3},
{a:'سَمِعَ',t:'samiʿa',n:'hij hoorde',th:'werkwoorden',b:'👂',g:'',mv:'يَسْمَعُ',s:1},
{a:'رَأَى',t:'raʾā',n:'hij zag',th:'werkwoorden',b:'👁️',g:'',mv:'يَرَى',s:2},
{a:'نَظَرَ',t:'naẓara',n:'hij keek',th:'werkwoorden',b:'',g:'',mv:'يَنْظُرُ',s:2},
{a:'تَكَلَّمَ',t:'takallama',n:'hij sprak',th:'werkwoorden',b:'💬',g:'',mv:'يَتَكَلَّمُ',s:3},
{a:'قَالَ',t:'qāla',n:'hij zei',th:'werkwoorden',b:'',g:'',mv:'يَقُولُ',s:2},
{a:'سَأَلَ',t:'saʾala',n:'hij vroeg',th:'werkwoorden',b:'❓',g:'',mv:'يَسْأَلُ',s:2},
{a:'أَجَابَ',t:'ajāba',n:'hij antwoordde',th:'werkwoorden',b:'',g:'',mv:'يُجِيبُ',s:3},
{a:'عَرَفَ',t:'ʿarafa',n:'hij wist, kende',th:'werkwoorden',b:'',g:'',mv:'يَعْرِفُ',s:2},
{a:'فَهِمَ',t:'fahima',n:'hij begreep',th:'werkwoorden',b:'💡',g:'',mv:'يَفْهَمُ',s:2},
{a:'عَمِلَ',t:'ʿamila',n:'hij werkte',th:'werkwoorden',b:'🛠️',g:'',mv:'يَعْمَلُ',s:2},
{a:'سَاعَدَ',t:'sāʿada',n:'hij hielp',th:'werkwoorden',b:'🤝',g:'',mv:'يُسَاعِدُ',s:3},
{a:'أَخَذَ',t:'akhadha',n:'hij nam',th:'werkwoorden',b:'',g:'',mv:'يَأْخُذُ',s:2},
{a:'أَعْطَى',t:'aʿṭā',n:'hij gaf',th:'werkwoorden',b:'🎁',g:'',mv:'يُعْطِي',s:3},
{a:'اِشْتَرَى',t:'ishtarā',n:'hij kocht',th:'werkwoorden',b:'🛒',g:'',mv:'يَشْتَرِي',s:3},
{a:'بَاعَ',t:'bāʿa',n:'hij verkocht',th:'werkwoorden',b:'',g:'',mv:'يَبِيعُ',s:3},
{a:'سَكَنَ',t:'sakana',n:'hij woonde',th:'werkwoorden',b:'🏠',g:'',mv:'يَسْكُنُ',s:2},
{a:'خَرَجَ',t:'kharaja',n:'hij ging naar buiten',th:'werkwoorden',b:'',g:'',mv:'يَخْرُجُ',s:2},
{a:'دَخَلَ',t:'dakhala',n:'hij ging naar binnen',th:'werkwoorden',b:'',g:'',mv:'يَدْخُلُ',s:2},
{a:'رَجَعَ',t:'rajaʿa',n:'hij keerde terug',th:'werkwoorden',b:'',g:'',mv:'يَرْجِعُ',s:2},
{a:'سَافَرَ',t:'sāfara',n:'hij reisde',th:'werkwoorden',b:'✈️',g:'',mv:'يُسَافِرُ',s:3},
{a:'وَجَدَ',t:'wajada',n:'hij vond',th:'werkwoorden',b:'',g:'',mv:'يَجِدُ',s:3},
{a:'حَمَلَ',t:'ḥamala',n:'hij droeg',th:'werkwoorden',b:'',g:'',mv:'يَحْمِلُ',s:3},
{a:'طَبَخَ',t:'ṭabakha',n:'hij kookte',th:'werkwoorden',b:'🍳',g:'',mv:'يَطْبُخُ',s:2},
{a:'غَسَلَ',t:'ghasala',n:'hij waste',th:'werkwoorden',b:'🧽',g:'',mv:'يَغْسِلُ',s:2},
{a:'ضَحِكَ',t:'ḍaḥika',n:'hij lachte',th:'werkwoorden',b:'😄',g:'',mv:'يَضْحَكُ',s:1},
{a:'بَكَى',t:'bakā',n:'hij huilde',th:'werkwoorden',b:'😭',g:'',mv:'يَبْكِي',s:2},
{a:'أَحَبَّ',t:'aḥabba',n:'hij hield van',th:'werkwoorden',b:'❤️',g:'',mv:'يُحِبُّ',s:2},
{a:'أَرَادَ',t:'arāda',n:'hij wilde',th:'werkwoorden',b:'',g:'',mv:'يُرِيدُ',s:3},
{a:'اِسْتَطَاعَ',t:'istaṭāʿa',n:'hij kon',th:'werkwoorden',b:'',g:'',mv:'يَسْتَطِيعُ',s:4},
{a:'كَانَ',t:'kāna',n:'hij was',th:'werkwoorden',b:'',g:'',mv:'يَكُونُ',s:3},
{a:'صَلَّى',t:'ṣallā',n:'hij bad',th:'werkwoorden',b:'🕌',g:'',mv:'يُصَلِّي',s:2},
{a:'حَفِظَ',t:'ḥafiẓa',n:'hij leerde uit het hoofd',th:'werkwoorden',b:'',g:'',mv:'يَحْفَظُ',s:2},
{a:'شَكَرَ',t:'shakara',n:'hij bedankte',th:'werkwoorden',b:'🙏',g:'',mv:'يَشْكُرُ',s:2},
{a:'رَسَمَ',t:'rasama',n:'hij tekende',th:'werkwoorden',b:'🎨',g:'',mv:'يَرْسُمُ',s:1},
{a:'غَنَّى',t:'ghannā',n:'hij zong',th:'werkwoorden',b:'🎵',g:'',mv:'يُغَنِّي',s:2},

/* ---------- natuur ---------- */
{a:'شَمْس',t:'shams',n:'zon',th:'natuur',b:'☀️',g:'v',mv:'شُمُوس',s:1},
{a:'قَمَر',t:'qamar',n:'maan',th:'natuur',b:'🌕',g:'m',mv:'أَقْمَار',s:1},
{a:'نَجْمَة',t:'najma',n:'ster',th:'natuur',b:'⭐',g:'v',mv:'نُجُوم',s:1},
{a:'سَمَاء',t:'samāʾ',n:'hemel, lucht',th:'natuur',b:'🌌',g:'v',mv:'سَمَاوَات',s:1},
{a:'أَرْض',t:'arḍ',n:'aarde, grond',th:'natuur',b:'🌍',g:'v',mv:'أَرَاضٍ',s:1},
{a:'بَحْر',t:'baḥr',n:'zee',th:'natuur',b:'🌊',g:'m',mv:'بِحَار',s:1},
{a:'نَهْر',t:'nahr',n:'rivier',th:'natuur',b:'🏞️',g:'m',mv:'أَنْهَار',s:1},
{a:'جَبَل',t:'jabal',n:'berg',th:'natuur',b:'⛰️',g:'m',mv:'جِبَال',s:1},
{a:'شَجَرَة',t:'shajara',n:'boom',th:'natuur',b:'🌳',g:'v',mv:'أَشْجَار',s:1},
{a:'زَهْرَة',t:'zahra',n:'bloem',th:'natuur',b:'🌷',g:'v',mv:'زُهُور',s:1},
{a:'وَرْدَة',t:'warda',n:'roos',th:'natuur',b:'🌹',g:'v',mv:'وُرُود',s:1},
{a:'عُشْب',t:'ʿushb',n:'gras',th:'natuur',b:'🌿',g:'m',mv:'أَعْشَاب',s:2},
{a:'حَجَر',t:'ḥajar',n:'steen',th:'natuur',b:'🪨',g:'m',mv:'حِجَارَة',s:2},
{a:'رَمْل',t:'raml',n:'zand',th:'natuur',b:'🏜️',g:'m',mv:'رِمَال',s:2},
{a:'نَار',t:'nār',n:'vuur',th:'natuur',b:'🔥',g:'v',mv:'نِيرَان',s:1},
{a:'هَوَاء',t:'hawāʾ',n:'lucht',th:'natuur',b:'💨',g:'m',mv:'',s:2},
{a:'رِيح',t:'rīḥ',n:'wind',th:'natuur',b:'🌬️',g:'v',mv:'رِيَاح',s:2},
{a:'مَطَر',t:'maṭar',n:'regen',th:'natuur',b:'🌧️',g:'m',mv:'أَمْطَار',s:1},
{a:'ثَلْج',t:'thalj',n:'sneeuw, ijs',th:'natuur',b:'❄️',g:'m',mv:'ثُلُوج',s:1},
{a:'سَحَاب',t:'saḥāb',n:'wolken',th:'natuur',b:'☁️',g:'m',mv:'',s:2},
{a:'صَحْرَاء',t:'ṣaḥrāʾ',n:'woestijn',th:'natuur',b:'🏜️',g:'v',mv:'صَحَارَى',s:2},
{a:'غَابَة',t:'ghāba',n:'bos',th:'natuur',b:'🌲',g:'v',mv:'غَابَات',s:2},
{a:'جَوّ',t:'jaww',n:'weer, sfeer',th:'natuur',b:'🌤️',g:'m',mv:'أَجْوَاء',s:2},
{a:'بَرْد',t:'bard',n:'kou',th:'natuur',b:'🥶',g:'m',mv:'',s:1},
{a:'حَرّ',t:'ḥarr',n:'hitte',th:'natuur',b:'🥵',g:'m',mv:'',s:1},
{a:'نُور',t:'nūr',n:'licht',th:'natuur',b:'💡',g:'m',mv:'أَنْوَار',s:2},
{a:'ظِلّ',t:'ẓill',n:'schaduw',th:'natuur',b:'',g:'m',mv:'ظِلَال',s:3},

/* ---------- kleding ---------- */
{a:'مَلَابِس',t:'malābis',n:'kleding',th:'kleding',b:'👕',g:'v',mv:'',s:1},
{a:'قَمِيص',t:'qamīṣ',n:'hemd',th:'kleding',b:'👔',g:'m',mv:'قُمْصَان',s:1},
{a:'بَنْطَال',t:'banṭāl',n:'broek',th:'kleding',b:'👖',g:'m',mv:'بَنْطَالَات',s:1},
{a:'فُسْتَان',t:'fustān',n:'jurk',th:'kleding',b:'👗',g:'m',mv:'فَسَاتِين',s:1},
{a:'حِذَاء',t:'ḥidhāʾ',n:'schoen',th:'kleding',b:'👟',g:'m',mv:'أَحْذِيَة',s:1},
{a:'جَوْرَب',t:'jawrab',n:'sok',th:'kleding',b:'🧦',g:'m',mv:'جَوَارِب',s:1},
{a:'قُبَّعَة',t:'qubbaʿa',n:'pet, hoed',th:'kleding',b:'🧢',g:'v',mv:'قُبَّعَات',s:1},
{a:'مِعْطَف',t:'miʿṭaf',n:'jas',th:'kleding',b:'🧥',g:'m',mv:'مَعَاطِف',s:1},
{a:'حِجَاب',t:'ḥijāb',n:'hoofddoek',th:'kleding',b:'🧕',g:'m',mv:'',s:2},
{a:'نَظَّارَة',t:'naẓẓāra',n:'bril',th:'kleding',b:'👓',g:'v',mv:'نَظَّارَات',s:1},
{a:'خَاتَم',t:'khātam',n:'ring',th:'kleding',b:'💍',g:'m',mv:'خَوَاتِم',s:2},
{a:'حِزَام',t:'ḥizām',n:'riem',th:'kleding',b:'',g:'m',mv:'أَحْزِمَة',s:3},
{a:'جَلَّابَة',t:'jallāba',n:'djellaba',th:'kleding',b:'',g:'v',mv:'جَلَالِيب',s:2,d:'Het Marokkaanse kledingstuk bij uitstek; het woord is in het Nederlands overgenomen.'},
{a:'ثَوْب',t:'thawb',n:'gewaad, kledingstuk',th:'kleding',b:'',g:'m',mv:'ثِيَاب',s:3},

/* ---------- stad en reizen ---------- */
{a:'مَدِينَة',t:'madīna',n:'stad',th:'stad',b:'🏙️',g:'v',mv:'مُدُن',s:1},
{a:'قَرْيَة',t:'qarya',n:'dorp',th:'stad',b:'🏘️',g:'v',mv:'قُرًى',s:2},
{a:'شَارِع',t:'shāriʿ',n:'straat',th:'stad',b:'🛣️',g:'m',mv:'شَوَارِع',s:1},
{a:'طَرِيق',t:'ṭarīq',n:'weg',th:'stad',b:'',g:'m',mv:'طُرُق',s:2},
{a:'سُوق',t:'sūq',n:'markt',th:'stad',b:'🏪',g:'m',mv:'أَسْوَاق',s:1},
{a:'دُكَّان',t:'dukkān',n:'winkel',th:'stad',b:'🛍️',g:'m',mv:'دَكَاكِين',s:2},
{a:'مَسْجِد',t:'masjid',n:'moskee',th:'stad',b:'🕌',g:'m',mv:'مَسَاجِد',s:1},
{a:'مُسْتَشْفَى',t:'mustashfā',n:'ziekenhuis',th:'stad',b:'🏥',g:'m',mv:'مُسْتَشْفَيَات',s:2},
{a:'طَبِيب',t:'ṭabīb',n:'dokter',th:'stad',b:'👨‍⚕️',g:'m',mv:'أَطِبَّاء',s:1},
{a:'صَيْدَلِيَّة',t:'ṣaydaliyya',n:'apotheek',th:'stad',b:'💊',g:'v',mv:'صَيْدَلِيَّات',s:3},
{a:'بَنْك',t:'bank',n:'bank',th:'stad',b:'🏦',g:'m',mv:'بُنُوك',s:2},
{a:'مَطَار',t:'maṭār',n:'vliegveld',th:'stad',b:'🛫',g:'m',mv:'مَطَارَات',s:2},
{a:'مَحَطَّة',t:'maḥaṭṭa',n:'station',th:'stad',b:'🚉',g:'v',mv:'مَحَطَّات',s:2},
{a:'سَيَّارَة',t:'sayyāra',n:'auto',th:'stad',b:'🚗',g:'v',mv:'سَيَّارَات',s:1},
{a:'حَافِلَة',t:'ḥāfila',n:'bus',th:'stad',b:'🚌',g:'v',mv:'حَافِلَات',s:1},
{a:'قِطَار',t:'qiṭār',n:'trein',th:'stad',b:'🚂',g:'m',mv:'قِطَارَات',s:1},
{a:'طَائِرَة',t:'ṭāʾira',n:'vliegtuig',th:'stad',b:'✈️',g:'v',mv:'طَائِرَات',s:1},
{a:'دَرَّاجَة',t:'darrāja',n:'fiets',th:'stad',b:'🚲',g:'v',mv:'دَرَّاجَات',s:1},
{a:'سَفِينَة',t:'safīna',n:'schip',th:'stad',b:'🚢',g:'v',mv:'سُفُن',s:2},
{a:'بَلَد',t:'balad',n:'land',th:'stad',b:'🗺️',g:'m',mv:'بُلْدَان',s:1},
{a:'عَاصِمَة',t:'ʿāṣima',n:'hoofdstad',th:'stad',b:'',g:'v',mv:'عَوَاصِم',s:3},
{a:'مَال',t:'māl',n:'geld, bezit',th:'stad',b:'💰',g:'m',mv:'أَمْوَال',s:2},
{a:'مَكْتَب',t:'maktab',n:'bureau, kantoor',th:'stad',b:'🗂️',g:'m',mv:'مَكَاتِب',s:2},
{a:'مَغْرِب',t:'maghrib',n:'Marokko, westen',th:'stad',b:'🇲🇦',g:'m',mv:'',s:1},
{a:'هُولَنْدَا',t:'hūlandā',n:'Nederland',th:'stad',b:'🇳🇱',g:'v',mv:'',s:1},
{a:'مَلِك',t:'malik',n:'koning',th:'stad',b:'👑',g:'m',mv:'مُلُوك',s:2},

/* ---------- functiewoorden ---------- */
{a:'فِي',t:'fī',n:'in',th:'functiewoorden',b:'',g:'',mv:'',s:1},
{a:'عَلَى',t:'ʿalā',n:'op',th:'functiewoorden',b:'',g:'',mv:'',s:1},
{a:'مِنْ',t:'min',n:'van, uit',th:'functiewoorden',b:'',g:'',mv:'',s:1},
{a:'إِلَى',t:'ilā',n:'naar',th:'functiewoorden',b:'',g:'',mv:'',s:1},
{a:'مَعَ',t:'maʿa',n:'met',th:'functiewoorden',b:'',g:'',mv:'',s:1},
{a:'عَنْ',t:'ʿan',n:'over, van',th:'functiewoorden',b:'',g:'',mv:'',s:2},
{a:'تَحْتَ',t:'taḥta',n:'onder',th:'functiewoorden',b:'',g:'',mv:'',s:1},
{a:'فَوْقَ',t:'fawqa',n:'boven',th:'functiewoorden',b:'',g:'',mv:'',s:1},
{a:'أَمَامَ',t:'amāma',n:'voor (plaats)',th:'functiewoorden',b:'',g:'',mv:'',s:2},
{a:'خَلْفَ',t:'khalfa',n:'achter',th:'functiewoorden',b:'',g:'',mv:'',s:2},
{a:'بَيْنَ',t:'bayna',n:'tussen',th:'functiewoorden',b:'',g:'',mv:'',s:2},
{a:'بِجَانِبِ',t:'bijānibi',n:'naast',th:'functiewoorden',b:'',g:'',mv:'',s:2},
{a:'قَبْلَ',t:'qabla',n:'voor (tijd)',th:'functiewoorden',b:'',g:'',mv:'',s:2},
{a:'بَعْدَ',t:'baʿda',n:'na',th:'functiewoorden',b:'',g:'',mv:'',s:2},
{a:'هٰذَا',t:'hādhā',n:'deze, dit (m)',th:'functiewoorden',b:'',g:'m',mv:'هٰؤُلَاءِ',s:1},
{a:'هٰذِهِ',t:'hādhihi',n:'deze, dit (v)',th:'functiewoorden',b:'',g:'v',mv:'هٰؤُلَاءِ',s:1},
{a:'ذٰلِكَ',t:'dhālika',n:'die, dat (m)',th:'functiewoorden',b:'',g:'m',mv:'أُولٰئِكَ',s:2},
{a:'تِلْكَ',t:'tilka',n:'die, dat (v)',th:'functiewoorden',b:'',g:'v',mv:'أُولٰئِكَ',s:2},
{a:'أَنَا',t:'anā',n:'ik',th:'functiewoorden',b:'',g:'',mv:'نَحْنُ',s:1},
{a:'أَنْتَ',t:'anta',n:'jij (m)',th:'functiewoorden',b:'',g:'m',mv:'أَنْتُمْ',s:1},
{a:'أَنْتِ',t:'anti',n:'jij (v)',th:'functiewoorden',b:'',g:'v',mv:'أَنْتُنَّ',s:1},
{a:'هُوَ',t:'huwa',n:'hij',th:'functiewoorden',b:'',g:'m',mv:'هُمْ',s:1},
{a:'هِيَ',t:'hiya',n:'zij',th:'functiewoorden',b:'',g:'v',mv:'هُنَّ',s:1},
{a:'نَحْنُ',t:'naḥnu',n:'wij',th:'functiewoorden',b:'',g:'',mv:'',s:1},
{a:'مَنْ',t:'man',n:'wie',th:'functiewoorden',b:'',g:'',mv:'',s:1},
{a:'مَا',t:'mā',n:'wat',th:'functiewoorden',b:'',g:'',mv:'',s:1},
{a:'أَيْنَ',t:'ayna',n:'waar',th:'functiewoorden',b:'',g:'',mv:'',s:1},
{a:'مَتَى',t:'matā',n:'wanneer',th:'functiewoorden',b:'',g:'',mv:'',s:1},
{a:'كَيْفَ',t:'kayfa',n:'hoe',th:'functiewoorden',b:'',g:'',mv:'',s:1},
{a:'لِمَاذَا',t:'limādhā',n:'waarom',th:'functiewoorden',b:'',g:'',mv:'',s:2},
{a:'كَمْ',t:'kam',n:'hoeveel',th:'functiewoorden',b:'',g:'',mv:'',s:1},
{a:'نَعَمْ',t:'naʿam',n:'ja',th:'functiewoorden',b:'',g:'',mv:'',s:1,d:'Marokkaans: إيه (īh) of واخا (wakha, "oké").'},
{a:'لَا',t:'lā',n:'nee, niet',th:'functiewoorden',b:'',g:'',mv:'',s:1},
{a:'لَيْسَ',t:'laysa',n:'is niet',th:'functiewoorden',b:'',g:'',mv:'',s:3},
{a:'هُنَا',t:'hunā',n:'hier',th:'functiewoorden',b:'',g:'',mv:'',s:1},
{a:'هُنَاكَ',t:'hunāka',n:'daar, er is',th:'functiewoorden',b:'',g:'',mv:'',s:1},
{a:'أَيْضًا',t:'ayḍan',n:'ook',th:'functiewoorden',b:'',g:'',mv:'',s:2},
{a:'لٰكِنْ',t:'lākin',n:'maar',th:'functiewoorden',b:'',g:'',mv:'',s:2},
{a:'لِأَنَّ',t:'liʾanna',n:'omdat',th:'functiewoorden',b:'',g:'',mv:'',s:3},
{a:'إِذَا',t:'idhā',n:'als, wanneer',th:'functiewoorden',b:'',g:'',mv:'',s:3},
{a:'كُلّ',t:'kull',n:'elk, alle',th:'functiewoorden',b:'',g:'m',mv:'',s:2},
{a:'بَعْض',t:'baʿḍ',n:'sommige',th:'functiewoorden',b:'',g:'m',mv:'',s:3},
{a:'جِدًّا',t:'jiddan',n:'heel, zeer',th:'functiewoorden',b:'',g:'',mv:'',s:1},
{a:'قَلِيل',t:'qalīl',n:'weinig',th:'functiewoorden',b:'',g:'m',mv:'',s:2},
{a:'كَثِير',t:'kathīr',n:'veel',th:'functiewoorden',b:'',g:'m',mv:'',s:2},
{a:'وَ',t:'wa',n:'en',th:'functiewoorden',b:'',g:'',mv:'',s:1},
{a:'أَوْ',t:'aw',n:'of',th:'functiewoorden',b:'',g:'',mv:'',s:2},
{a:'ثُمَّ',t:'thumma',n:'daarna',th:'functiewoorden',b:'',g:'',mv:'',s:3},
{a:'إِنَّ',t:'inna',n:'voorwaar, werkelijk',th:'functiewoorden',b:'',g:'',mv:'',s:4},
{a:'قَدْ',t:'qad',n:'reeds, wellicht',th:'functiewoorden',b:'',g:'',mv:'',s:4},

/* ---------- begroetingen ---------- */
{a:'سَلَام',t:'salām',n:'vrede',th:'begroetingen',b:'☮️',g:'m',mv:'',s:1},
{a:'مَرْحَبًا',t:'marḥaban',n:'hallo',th:'begroetingen',b:'👋',g:'',mv:'',s:1},
{a:'أَهْلًا',t:'ahlan',n:'welkom, hoi',th:'begroetingen',b:'',g:'',mv:'',s:1},
{a:'شُكْرًا',t:'shukran',n:'dank je',th:'begroetingen',b:'🙏',g:'',mv:'',s:1},
{a:'عَفْوًا',t:'ʿafwan',n:'graag gedaan, pardon',th:'begroetingen',b:'',g:'',mv:'',s:1},
{a:'آسِف',t:'āsif',n:'sorry (m)',th:'begroetingen',b:'',g:'m',mv:'',s:1},
{a:'آسِفَة',t:'āsifa',n:'sorry (v)',th:'begroetingen',b:'',g:'v',mv:'',s:1},
{a:'تَفَضَّلْ',t:'tafaḍḍal',n:'alstublieft, ga uw gang',th:'begroetingen',b:'',g:'',mv:'',s:2},
{a:'مَبْرُوك',t:'mabrūk',n:'gefeliciteerd',th:'begroetingen',b:'🎉',g:'',mv:'',s:1},
{a:'إِنْ شَاءَ اللّٰهُ',t:'in shāʾa llāh',n:'als God het wil',th:'begroetingen',b:'',g:'',mv:'',s:1},
{a:'الْحَمْدُ لِلّٰهِ',t:'al-ḥamdu li-llāh',n:'lof zij God',th:'begroetingen',b:'',g:'',mv:'',s:1},
{a:'بِسْمِ اللّٰهِ',t:'bismi llāh',n:'in de naam van God',th:'begroetingen',b:'',g:'',mv:'',s:1}
];
