import type { Zin } from './soorten'


/* ============================================================
   ZINNEN — nuttige zinnen, oplopend in complexiteit
   ------------------------------------------------------------
   a  Arabisch, gevocaliseerd
   t  transcriptie
   n  Nederlands
   n2 niveau 1-4, loopt gelijk met de sporen
   c  categorie
   ============================================================ */
export const ZINNEN: Zin[] = [
/* --- niveau 1: begroeten en het allernodigste --- */
{a:'اَلسَّلَامُ عَلَيْكُمْ',t:'as-salāmu ʿalaykum',n:'Vrede zij met u',n2:1,c:'begroeten'},
{a:'وَعَلَيْكُمُ السَّلَام',t:'wa-ʿalaykumu s-salām',n:'En met u zij vrede',n2:1,c:'begroeten'},
{a:'صَبَاحُ الْخَيْرِ',t:'ṣabāḥu l-khayr',n:'Goedemorgen',n2:1,c:'begroeten'},
{a:'صَبَاحُ النُّورِ',t:'ṣabāḥu n-nūr',n:'Goedemorgen (antwoord)',n2:1,c:'begroeten'},
{a:'مَسَاءُ الْخَيْرِ',t:'masāʾu l-khayr',n:'Goedenavond',n2:1,c:'begroeten'},
{a:'كَيْفَ حَالُكَ؟',t:'kayfa ḥāluka?',n:'Hoe gaat het met je? (tegen een man)',n2:1,c:'begroeten'},
{a:'كَيْفَ حَالُكِ؟',t:'kayfa ḥāluki?',n:'Hoe gaat het met je? (tegen een vrouw)',n2:1,c:'begroeten'},
{a:'بِخَيْرٍ، الْحَمْدُ لِلّٰهِ',t:'bi-khayrin, al-ḥamdu li-llāh',n:'Goed, lof zij God',n2:1,c:'begroeten'},
{a:'مَا اسْمُكَ؟',t:'mā smuka?',n:'Hoe heet je? (tegen een man)',n2:1,c:'kennismaken'},
{a:'اِسْمِي أَحْمَد',t:'ismī aḥmad',n:'Ik heet Ahmed',n2:1,c:'kennismaken'},
{a:'تَشَرَّفْنَا',t:'tasharrafnā',n:'Aangenaam kennis te maken',n2:1,c:'kennismaken'},
{a:'مَعَ السَّلَامَةِ',t:'maʿa s-salāma',n:'Tot ziens',n2:1,c:'begroeten'},
{a:'إِلَى اللِّقَاءِ',t:'ilā l-liqāʾ',n:'Tot de volgende keer',n2:1,c:'begroeten'},
{a:'تُصْبِحُ عَلَى خَيْرٍ',t:'tuṣbiḥu ʿalā khayr',n:'Welterusten',n2:1,c:'begroeten'},
{a:'شُكْرًا جَزِيلًا',t:'shukran jazīlan',n:'Hartelijk dank',n2:1,c:'beleefdheid'},
{a:'عَفْوًا',t:'ʿafwan',n:'Graag gedaan',n2:1,c:'beleefdheid'},
{a:'مِنْ فَضْلِكَ',t:'min faḍlika',n:'Alsjeblieft (verzoek, tegen een man)',n2:1,c:'beleefdheid'},
{a:'آسِف',t:'āsif',n:'Sorry',n2:1,c:'beleefdheid'},
{a:'لَا بَأْسَ',t:'lā baʾsa',n:'Geeft niet',n2:1,c:'beleefdheid'},
{a:'نَعَمْ',t:'naʿam',n:'Ja',n2:1,c:'beleefdheid'},
{a:'لَا',t:'lā',n:'Nee',n2:1,c:'beleefdheid'},
{a:'هٰذَا كِتَابٌ',t:'hādhā kitābun',n:'Dit is een boek',n2:1,c:'aanwijzen'},
{a:'هٰذِهِ مَدْرَسَةٌ',t:'hādhihi madrasatun',n:'Dit is een school',n2:1,c:'aanwijzen'},
{a:'هٰذَا بَيْتِي',t:'hādhā baytī',n:'Dit is mijn huis',n2:1,c:'aanwijzen'},
{a:'هٰذِهِ أُمِّي',t:'hādhihi ummī',n:'Dit is mijn moeder',n2:1,c:'familie'},
{a:'أَنَا وَلَدٌ',t:'anā waladun',n:'Ik ben een jongen',n2:1,c:'kennismaken'},
{a:'أَنَا بِنْتٌ',t:'anā bintun',n:'Ik ben een meisje',n2:1,c:'kennismaken'},
{a:'الْبَابُ مَفْتُوحٌ',t:'al-bābu maftūḥun',n:'De deur is open',n2:1,c:'beschrijven'},
{a:'الْجَوُّ جَمِيلٌ',t:'al-jawwu jamīlun',n:'Het weer is mooi',n2:1,c:'beschrijven'},
{a:'الْقِطُّ صَغِيرٌ',t:'al-qiṭṭu ṣaghīrun',n:'De kat is klein',n2:1,c:'beschrijven'},
{a:'أَنَا جَائِعٌ',t:'anā jāʾiʿun',n:'Ik heb honger',n2:1,c:'gevoel'},
{a:'أَنَا عَطْشَانُ',t:'anā ʿaṭshānu',n:'Ik heb dorst',n2:1,c:'gevoel'},
{a:'أَنَا مُتْعَبٌ',t:'anā mutʿabun',n:'Ik ben moe',n2:1,c:'gevoel'},
{a:'أَنَا سَعِيدٌ',t:'anā saʿīdun',n:'Ik ben blij',n2:1,c:'gevoel'},
{a:'أُرِيدُ مَاءً',t:'urīdu māʾan',n:'Ik wil water',n2:1,c:'vragen'},
{a:'أُرِيدُ خُبْزًا',t:'urīdu khubzan',n:'Ik wil brood',n2:1,c:'vragen'},
{a:'أَيْنَ الْحَمَّامُ؟',t:'ayna l-ḥammām?',n:'Waar is de badkamer?',n2:1,c:'vragen'},
{a:'مَا هٰذَا؟',t:'mā hādhā?',n:'Wat is dit?',n2:1,c:'vragen'},
{a:'كَمْ عُمْرُكَ؟',t:'kam ʿumruka?',n:'Hoe oud ben je?',n2:1,c:'vragen'},
{a:'عُمْرِي عَشْرُ سَنَوَاتٍ',t:'ʿumrī ʿashru sanawātin',n:'Ik ben tien jaar',n2:1,c:'vragen'},

/* --- niveau 2: dagelijks leven --- */
{a:'أَنَا مِنْ هُولَنْدَا',t:'anā min hūlandā',n:'Ik kom uit Nederland',n2:2,c:'kennismaken'},
{a:'عَائِلَتِي مِنَ الْمَغْرِبِ',t:'ʿāʾilatī mina l-maghrib',n:'Mijn familie komt uit Marokko',n2:2,c:'kennismaken'},
{a:'أَتَكَلَّمُ الْعَرَبِيَّةَ قَلِيلًا',t:'atakallamu l-ʿarabiyyata qalīlan',n:'Ik spreek een beetje Arabisch',n2:2,c:'kennismaken'},
{a:'لَا أَفْهَمُ',t:'lā afhamu',n:'Ik begrijp het niet',n2:2,c:'kennismaken'},
{a:'مَرَّةً أُخْرَى، مِنْ فَضْلِكَ',t:'marratan ukhrā, min faḍlik',n:'Nog een keer, alsjeblieft',n2:2,c:'kennismaken'},
{a:'كَيْفَ تَقُولُ هٰذَا بِالْعَرَبِيَّةِ؟',t:'kayfa taqūlu hādhā bi-l-ʿarabiyya?',n:'Hoe zeg je dit in het Arabisch?',n2:2,c:'kennismaken'},
{a:'عِنْدِي أَخٌ وَأُخْتٌ',t:'ʿindī akhun wa-ukhtun',n:'Ik heb een broer en een zus',n2:2,c:'familie'},
{a:'أَبِي طَبِيبٌ',t:'abī ṭabībun',n:'Mijn vader is dokter',n2:2,c:'familie'},
{a:'أُمِّي فِي الْمَطْبَخِ',t:'ummī fī l-maṭbakh',n:'Mijn moeder is in de keuken',n2:2,c:'familie'},
{a:'أَخِي فِي الْمَدْرَسَةِ',t:'akhī fī l-madrasa',n:'Mijn broer is op school',n2:2,c:'familie'},
{a:'نَحْنُ أُسْرَةٌ كَبِيرَةٌ',t:'naḥnu usratun kabīratun',n:'Wij zijn een grote familie',n2:2,c:'familie'},
{a:'أَذْهَبُ إِلَى الْمَدْرَسَةِ',t:'adhhabu ilā l-madrasa',n:'Ik ga naar school',n2:2,c:'dagelijks'},
{a:'أَقْرَأُ كِتَابًا',t:'aqraʾu kitāban',n:'Ik lees een boek',n2:2,c:'dagelijks'},
{a:'أَكْتُبُ الْوَاجِبَ',t:'aktubu l-wājib',n:'Ik maak mijn huiswerk',n2:2,c:'dagelijks'},
{a:'نَأْكُلُ الْفَطُورَ',t:'naʾkulu l-faṭūr',n:'Wij eten ontbijt',n2:2,c:'dagelijks'},
{a:'أَشْرَبُ الشَّايَ',t:'ashrabu sh-shāy',n:'Ik drink thee',n2:2,c:'dagelijks'},
{a:'أَلْعَبُ مَعَ أَصْدِقَائِي',t:'alʿabu maʿa aṣdiqāʾī',n:'Ik speel met mijn vrienden',n2:2,c:'dagelijks'},
{a:'أَنَامُ مُبَكِّرًا',t:'anāmu mubakkiran',n:'Ik ga vroeg slapen',n2:2,c:'dagelijks'},
{a:'أُسَاعِدُ أُمِّي',t:'usāʿidu ummī',n:'Ik help mijn moeder',n2:2,c:'dagelijks'},
{a:'الْكِتَابُ عَلَى الطَّاوِلَةِ',t:'al-kitābu ʿalā ṭ-ṭāwila',n:'Het boek ligt op de tafel',n2:2,c:'beschrijven'},
{a:'الْقِطُّ تَحْتَ الْكُرْسِيِّ',t:'al-qiṭṭu taḥta l-kursiyy',n:'De kat zit onder de stoel',n2:2,c:'beschrijven'},
{a:'الْحَقِيبَةُ فِي الْغُرْفَةِ',t:'al-ḥaqībatu fī l-ghurfa',n:'De tas ligt in de kamer',n2:2,c:'beschrijven'},
{a:'الْمَدْرَسَةُ قَرِيبَةٌ مِنَ الْبَيْتِ',t:'al-madrasatu qarībatun mina l-bayt',n:'De school is dichtbij het huis',n2:2,c:'beschrijven'},
{a:'هُنَاكَ شَجَرَةٌ فِي الْحَدِيقَةِ',t:'hunāka shajaratun fī l-ḥadīqa',n:'Er staat een boom in de tuin',n2:2,c:'beschrijven'},
{a:'كَمْ هٰذَا؟',t:'kam hādhā?',n:'Hoeveel kost dit?',n2:2,c:'winkelen'},
{a:'هٰذَا غَالٍ',t:'hādhā ghālin',n:'Dat is duur',n2:2,c:'winkelen'},
{a:'أُرِيدُ كِيلُو تُفَّاحٍ',t:'urīdu kīlū tuffāḥin',n:'Ik wil een kilo appels',n2:2,c:'winkelen'},
{a:'عِنْدَكَ خُبْزٌ؟',t:'ʿindaka khubzun?',n:'Heb je brood?',n2:2,c:'winkelen'},
{a:'الْحِسَابَ مِنْ فَضْلِكَ',t:'al-ḥisāba min faḍlik',n:'De rekening, alsjeblieft',n2:2,c:'winkelen'},
{a:'كَمِ السَّاعَةُ؟',t:'kami s-sāʿa?',n:'Hoe laat is het?',n2:2,c:'tijd'},
{a:'السَّاعَةُ الثَّالِثَةُ',t:'as-sāʿatu th-thālitha',n:'Het is drie uur',n2:2,c:'tijd'},
{a:'الْيَوْمُ الْجُمُعَةُ',t:'al-yawmu l-jumuʿa',n:'Vandaag is het vrijdag',n2:2,c:'tijd'},
{a:'غَدًا عُطْلَةٌ',t:'ghadan ʿuṭlatun',n:'Morgen is het vakantie',n2:2,c:'tijd'},
{a:'أَرَاكَ غَدًا',t:'arāka ghadan',n:'Tot morgen',n2:2,c:'tijd'},
{a:'أَنَا مَرِيضٌ',t:'anā marīḍun',n:'Ik ben ziek',n2:2,c:'gevoel'},
{a:'رَأْسِي يُؤْلِمُنِي',t:'raʾsī yuʾlimunī',n:'Ik heb hoofdpijn',n2:2,c:'gevoel'},
{a:'أُحِبُّ الْقِرَاءَةَ',t:'uḥibbu l-qirāʾa',n:'Ik houd van lezen',n2:2,c:'gevoel'},
{a:'لَا أُحِبُّ الْبَرْدَ',t:'lā uḥibbu l-bard',n:'Ik houd niet van kou',n2:2,c:'gevoel'},
{a:'مَا لَوْنُ الْبَيْتِ؟',t:'mā lawnu l-bayt?',n:'Welke kleur heeft het huis?',n2:2,c:'vragen'},
{a:'الْبَيْتُ أَبْيَضُ',t:'al-baytu abyaḍu',n:'Het huis is wit',n2:2,c:'beschrijven'},
{a:'أَيْنَ تَسْكُنُ؟',t:'ayna taskunu?',n:'Waar woon je?',n2:2,c:'vragen'},
{a:'أَسْكُنُ فِي أَمْسْتِرْدَام',t:'askunu fī amstirdām',n:'Ik woon in Amsterdam',n2:2,c:'vragen'},

/* --- niveau 3: zinsbouw en verband --- */
{a:'ذَهَبْتُ إِلَى السُّوقِ مَعَ أُمِّي',t:'dhahabtu ilā s-sūqi maʿa ummī',n:'Ik ging met mijn moeder naar de markt',n2:3,c:'verhalen'},
{a:'اِشْتَرَيْنَا الْخُبْزَ وَالْحَلِيبَ',t:'ishtaraynā l-khubza wa-l-ḥalīb',n:'Wij kochten brood en melk',n2:3,c:'verhalen'},
{a:'كَانَ الْجَوُّ بَارِدًا أَمْسِ',t:'kāna l-jawwu bāridan ams',n:'Het weer was gisteren koud',n2:3,c:'verhalen'},
{a:'لَمْ أَذْهَبْ إِلَى الْمَدْرَسَةِ',t:'lam adhhab ilā l-madrasa',n:'Ik ben niet naar school gegaan',n2:3,c:'verhalen'},
{a:'سَأَزُورُ جَدَّتِي غَدًا',t:'saʾazūru jaddatī ghadan',n:'Ik ga morgen mijn oma bezoeken',n2:3,c:'verhalen'},
{a:'عِنْدَمَا وَصَلْتُ، كَانَ الْبَابُ مُغْلَقًا',t:'ʿindamā waṣaltu, kāna l-bābu mughlaqan',n:'Toen ik aankwam, was de deur dicht',n2:3,c:'verhalen'},
{a:'قَرَأْتُ الْكِتَابَ لِأَنَّهُ مُمْتِعٌ',t:'qaraʾtu l-kitāba li-annahu mumtiʿun',n:'Ik las het boek omdat het boeiend is',n2:3,c:'verband'},
{a:'أُرِيدُ أَنْ أَتَعَلَّمَ الْعَرَبِيَّةَ',t:'urīdu an ataʿallama l-ʿarabiyya',n:'Ik wil Arabisch leren',n2:3,c:'verband'},
{a:'يَجِبُ أَنْ نَدْرُسَ كُلَّ يَوْمٍ',t:'yajibu an nadrusa kulla yawmin',n:'Wij moeten elke dag studeren',n2:3,c:'verband'},
{a:'يُمْكِنُنِي أَنْ أُسَاعِدَكَ',t:'yumkinunī an usāʿidaka',n:'Ik kan je helpen',n2:3,c:'verband'},
{a:'إِذَا دَرَسْتَ، سَتَنْجَحُ',t:'idhā darasta, satanjaḥu',n:'Als je studeert, zul je slagen',n2:3,c:'verband'},
{a:'الطَّالِبُ الَّذِي يَقْرَأُ كَثِيرًا يَتَعَلَّمُ سَرِيعًا',t:'aṭ-ṭālibu lladhī yaqraʾu kathīran yataʿallamu sarīʿan',n:'De leerling die veel leest, leert snel',n2:3,c:'verband'},
{a:'هٰذَا هُوَ الْبَيْتُ الَّذِي وُلِدْتُ فِيهِ',t:'hādhā huwa l-baytu lladhī wulidtu fīhi',n:'Dit is het huis waarin ik geboren ben',n2:3,c:'verband'},
{a:'بَابُ الْبَيْتِ مَفْتُوحٌ',t:'bābu l-bayti maftūḥun',n:'De deur van het huis staat open',n2:3,c:'idafa'},
{a:'كِتَابُ الطَّالِبِ عَلَى الْمَكْتَبِ',t:'kitābu ṭ-ṭālibi ʿalā l-maktab',n:'Het boek van de leerling ligt op het bureau',n2:3,c:'idafa'},
{a:'مِفْتَاحُ السَّيَّارَةِ فِي جَيْبِي',t:'miftāḥu s-sayyārati fī jaybī',n:'De autosleutel zit in mijn zak',n2:3,c:'idafa'},
{a:'مُعَلِّمُ اللُّغَةِ الْعَرَبِيَّةِ رَجُلٌ طَيِّبٌ',t:'muʿallimu l-lughati l-ʿarabiyyati rajulun ṭayyibun',n:'De leraar Arabisch is een goede man',n2:3,c:'idafa'},
{a:'مَاذَا فَعَلْتَ أَمْسِ؟',t:'mādhā faʿalta ams?',n:'Wat heb je gisteren gedaan?',n2:3,c:'vragen'},
{a:'لِمَاذَا تَأَخَّرْتَ؟',t:'limādhā taʾakhkharta?',n:'Waarom ben je te laat?',n2:3,c:'vragen'},
{a:'مَعَ مَنْ ذَهَبْتَ؟',t:'maʿa man dhahabta?',n:'Met wie ben je gegaan?',n2:3,c:'vragen'},
{a:'هَلْ تُرِيدُ شَيْئًا آخَرَ؟',t:'hal turīdu shayʾan ākhara?',n:'Wil je nog iets anders?',n2:3,c:'vragen'},
{a:'لَيْسَ عِنْدِي وَقْتٌ',t:'laysa ʿindī waqtun',n:'Ik heb geen tijd',n2:3,c:'ontkennen'},
{a:'لَمْ أَرَ أَحَدًا',t:'lam ara aḥadan',n:'Ik heb niemand gezien',n2:3,c:'ontkennen'},
{a:'لَنْ أَنْسَى هٰذَا الْيَوْمَ',t:'lan ansā hādhā l-yawm',n:'Ik zal deze dag niet vergeten',n2:3,c:'ontkennen'},
{a:'مَا زِلْتُ أَتَعَلَّمُ',t:'mā ziltu ataʿallamu',n:'Ik ben nog steeds aan het leren',n2:3,c:'ontkennen'},
{a:'اِفْتَحِ الْبَابَ مِنْ فَضْلِكَ',t:'iftaḥi l-bāba min faḍlik',n:'Doe de deur open, alsjeblieft',n2:3,c:'gebieden'},
{a:'اِسْتَمِعْ جَيِّدًا',t:'istamiʿ jayyidan',n:'Luister goed',n2:3,c:'gebieden'},
{a:'اُكْتُبِ الْجَوَابَ',t:'uktubi l-jawāb',n:'Schrijf het antwoord op',n2:3,c:'gebieden'},
{a:'لَا تَنْسَ الْوَاجِبَ',t:'lā tansa l-wājib',n:'Vergeet je huiswerk niet',n2:3,c:'gebieden'},
{a:'تَعَالَ هُنَا',t:'taʿāla hunā',n:'Kom hier',n2:3,c:'gebieden'},
{a:'الْعَرَبِيَّةُ لُغَةٌ جَمِيلَةٌ وَلٰكِنَّهَا صَعْبَةٌ',t:'al-ʿarabiyyatu lughatun jamīlatun wa-lākinnahā ṣaʿbatun',n:'Het Arabisch is een mooie taal, maar hij is moeilijk',n2:3,c:'verband'},
{a:'كُلَّمَا قَرَأْتُ أَكْثَرَ، فَهِمْتُ أَكْثَرَ',t:'kullamā qaraʾtu akthara, fahimtu akthara',n:'Hoe meer ik lees, hoe meer ik begrijp',n2:3,c:'verband'},
{a:'أَنَا مَشْغُولٌ الْآنَ، سَأَتَّصِلُ بِكَ لَاحِقًا',t:'anā mashghūlun al-āna, saʾattaṣilu bika lāḥiqan',n:'Ik heb het nu druk, ik bel je later',n2:3,c:'dagelijks'},
{a:'هَلْ يُمْكِنُكَ أَنْ تَتَكَلَّمَ بِبُطْءٍ؟',t:'hal yumkinuka an tatakallama bi-buṭʾin?',n:'Kun je langzamer praten?',n2:3,c:'kennismaken'},
{a:'أَعْتَذِرُ عَنِ التَّأْخِيرِ',t:'aʿtadhiru ʿani t-taʾkhīr',n:'Mijn excuses voor de vertraging',n2:3,c:'beleefdheid'},
{a:'بَارَكَ اللّٰهُ فِيكَ',t:'bāraka llāhu fīk',n:'Moge God je zegenen (dankbetuiging)',n2:3,c:'beleefdheid'},
{a:'كُلُّ عَامٍ وَأَنْتُمْ بِخَيْرٍ',t:'kullu ʿāmin wa-antum bi-khayr',n:'Een gelukkig nieuw jaar / prettige feestdagen',n2:3,c:'beleefdheid'},
{a:'رَمَضَان مُبَارَك',t:'ramaḍān mubārak',n:'Gezegende ramadan',n2:3,c:'beleefdheid'},
{a:'فِي الصَّبَاحِ أَشْرَبُ الْقَهْوَةَ وَأَقْرَأُ الْجَرِيدَةَ',t:'fī ṣ-ṣabāḥi ashrabu l-qahwata wa-aqraʾu l-jarīda',n:'\'s Ochtends drink ik koffie en lees ik de krant',n2:3,c:'dagelijks'},
{a:'بَعْدَ الْعَشَاءِ نَجْلِسُ مَعًا',t:'baʿda l-ʿashāʾi najlisu maʿan',n:'Na het avondeten zitten wij samen',n2:3,c:'dagelijks'},
{a:'الْأَطْفَالُ يَلْعَبُونَ فِي الْحَدِيقَةِ',t:'al-aṭfālu yalʿabūna fī l-ḥadīqa',n:'De kinderen spelen in de tuin',n2:3,c:'beschrijven'},

/* --- niveau 4: verzorgd en klassiek --- */
{a:'إِنَّ الْعِلْمَ نُورٌ',t:'inna l-ʿilma nūrun',n:'Kennis is licht',n2:4,c:'spreekwoord'},
{a:'اُطْلُبُوا الْعِلْمَ مِنَ الْمَهْدِ إِلَى اللَّحْدِ',t:'uṭlubū l-ʿilma mina l-mahdi ilā l-laḥd',n:'Zoek kennis van de wieg tot het graf',n2:4,c:'spreekwoord'},
{a:'الصَّبْرُ مِفْتَاحُ الْفَرَجِ',t:'aṣ-ṣabru miftāḥu l-faraj',n:'Geduld is de sleutel tot verlichting',n2:4,c:'spreekwoord'},
{a:'مَنْ جَدَّ وَجَدَ',t:'man jadda wajada',n:'Wie zich inspant, vindt',n2:4,c:'spreekwoord'},
{a:'الْوَقْتُ كَالسَّيْفِ',t:'al-waqtu ka-s-sayf',n:'Tijd is als een zwaard',n2:4,c:'spreekwoord'},
{a:'خَيْرُ الْكَلَامِ مَا قَلَّ وَدَلَّ',t:'khayru l-kalāmi mā qalla wa-dalla',n:'De beste woorden zijn er weinig die veel zeggen',n2:4,c:'spreekwoord'},
{a:'لَا تُؤَجِّلْ عَمَلَ الْيَوْمِ إِلَى الْغَدِ',t:'lā tuʾajjil ʿamala l-yawmi ilā l-ghad',n:'Stel het werk van vandaag niet uit tot morgen',n2:4,c:'spreekwoord'},
{a:'رُبَّ أَخٍ لَمْ تَلِدْهُ أُمُّكَ',t:'rubba akhin lam talidhu ummuka',n:'Menige broeder is niet door je moeder gebaard',n2:4,c:'spreekwoord'},
{a:'قَدْ أَفْلَحَ مَنْ تَزَكَّى',t:'qad aflaḥa man tazakkā',n:'Waarlijk geslaagd is wie zich loutert',n2:4,c:'klassiek'},
{a:'وَقُلْ رَبِّ زِدْنِي عِلْمًا',t:'wa-qul rabbi zidnī ʿilman',n:'En zeg: mijn Heer, vermeerder mij in kennis',n2:4,c:'klassiek'},
{a:'إِنَّ مَعَ الْعُسْرِ يُسْرًا',t:'inna maʿa l-ʿusri yusran',n:'Voorwaar, met de moeilijkheid komt verlichting',n2:4,c:'klassiek'},
{a:'وَاللّٰهُ يَعْلَمُ وَأَنْتُمْ لَا تَعْلَمُونَ',t:'wa-llāhu yaʿlamu wa-antum lā taʿlamūna',n:'God weet, en jullie weten niet',n2:4,c:'klassiek'},
{a:'الْحَمْدُ لِلّٰهِ رَبِّ الْعَالَمِينَ',t:'al-ḥamdu li-llāhi rabbi l-ʿālamīn',n:'Lof zij God, Heer der werelden',n2:4,c:'klassiek'},
{a:'يَسْتَطِيعُ الْمَرْءُ أَنْ يَتَعَلَّمَ فِي أَيِّ سِنٍّ',t:'yastaṭīʿu l-marʾu an yataʿallama fī ayyi sinnin',n:'Een mens kan op elke leeftijd leren',n2:4,c:'verzorgd'},
{a:'لَا يَزَالُ الطِّبُّ يَتَطَوَّرُ بِسُرْعَةٍ',t:'lā yazālu ṭ-ṭibbu yataṭawwaru bi-surʿatin',n:'De geneeskunde blijft zich snel ontwikkelen',n2:4,c:'verzorgd'},
{a:'مِنَ الْمُهِمِّ أَنْ نَفْهَمَ السِّيَاقَ',t:'mina l-muhimmi an nafhama s-siyāq',n:'Het is belangrijk dat wij de context begrijpen',n2:4,c:'verzorgd'},
{a:'أُصِيبَ الرَّجُلُ بِمَرَضٍ خَطِيرٍ',t:'uṣība r-rajulu bi-maraḍin khaṭīrin',n:'De man werd getroffen door een ernstige ziekte',n2:4,c:'verzorgd'},
{a:'تُعْتَبَرُ اللُّغَةُ الْعَرَبِيَّةُ مِنْ أَقْدَمِ اللُّغَاتِ الْحَيَّةِ',t:'tuʿtabaru l-lughatu l-ʿarabiyyatu min aqdami l-lughāti l-ḥayya',n:'Het Arabisch wordt beschouwd als een van de oudste levende talen',n2:4,c:'verzorgd'},
{a:'كُتِبَ هٰذَا الْكِتَابُ قَبْلَ أَلْفِ عَامٍ',t:'kutiba hādhā l-kitābu qabla alfi ʿāmin',n:'Dit boek is duizend jaar geleden geschreven',n2:4,c:'verzorgd'},
{a:'جَاءَ الرَّجُلُ وَهُوَ يَبْتَسِمُ',t:'jāʾa r-rajulu wa-huwa yabtasimu',n:'De man kwam glimlachend binnen',n2:4,c:'verzorgd'},
{a:'ذَهَبَ الطَّبِيبُ إِلَى الْمَرِيضِ فَوْرَ وُصُولِ الْخَبَرِ',t:'dhahaba ṭ-ṭabību ilā l-marīḍi fawra wuṣūli l-khabar',n:'De arts ging naar de patiënt zodra het bericht binnenkwam',n2:4,c:'verzorgd'},
{a:'لِكُلِّ دَاءٍ دَوَاءٌ',t:'li-kulli dāʾin dawāʾun',n:'Voor elke kwaal is er een geneesmiddel',n2:4,c:'spreekwoord'},
{a:'الْعَقْلُ السَّلِيمُ فِي الْجِسْمِ السَّلِيمِ',t:'al-ʿaqlu s-salīmu fī l-jismi s-salīm',n:'Een gezonde geest in een gezond lichaam',n2:4,c:'spreekwoord'},
{a:'مَنْ لَا يَشْكُرِ النَّاسَ لَا يَشْكُرِ اللّٰهَ',t:'man lā yashkuri n-nāsa lā yashkuri llāh',n:'Wie de mensen niet dankt, dankt God niet',n2:4,c:'klassiek'}
];
