import type { Dua, Hifz } from './soorten'

/* =============================================================================
   UIT JE HOOFD LEREN — de korte soera's en de vaste teksten van het gebed.
   Per regel: Arabisch, klank in Nederlandse letters, en de betekenis.
   De betekenis is een weergave in het Nederlands; de Koran zelf is het Arabisch.
============================================================================= */
export const HIFZ: Hifz[] = [
 {id:'h-fatiha', naam:'Al-Fatiha', ar:'الفاتحة', nr:1, aya:7, soort:'soera', waarom:'In elke rak\'a van elk gebed. Deze eerst.',
  r:[['بِسْمِ اللَّهِ الرَّحْمَٰنِ الرَّحِيمِ','Bismillahi r-rahmani r-rahim','In de naam van Allah, de Erbarmer, de Barmhartige'],
     ['الْحَمْدُ لِلَّهِ رَبِّ الْعَالَمِينَ','Alhamdu lillahi rabbi l-\'alamin','Alle lof is voor Allah, de Heer van de werelden'],
     ['الرَّحْمَٰنِ الرَّحِيمِ','Ar-rahmani r-rahim','De Erbarmer, de Barmhartige'],
     ['مَالِكِ يَوْمِ الدِّينِ','Maliki yawmi d-din','Meester van de dag van het oordeel'],
     ['إِيَّاكَ نَعْبُدُ وَإِيَّاكَ نَسْتَعِينُ','Iyyaka na\'budu wa iyyaka nasta\'in','Alleen U aanbidden wij en alleen U vragen wij om hulp'],
     ['اهْدِنَا الصِّرَاطَ الْمُسْتَقِيمَ','Ihdina s-sirata l-mustaqim','Leid ons op het rechte pad'],
     ['صِرَاطَ الَّذِينَ أَنْعَمْتَ عَلَيْهِمْ غَيْرِ الْمَغْضُوبِ عَلَيْهِمْ وَلَا الضَّالِّينَ','Sirata lladhina an\'amta \'alayhim ghayri l-maghdubi \'alayhim wa la d-dallin','Het pad van hen die U begunstigd hebt, niet van hen op wie toorn rust en niet van de dwalenden']]},

 {id:'h-nas', naam:'An-Nas', ar:'الناس', nr:114, aya:6, soort:'soera', waarom:'De laatste soera. Bescherming, elke avond.',
  r:[['قُلْ أَعُوذُ بِرَبِّ النَّاسِ','Qul a\'udhu bi-rabbi n-nas','Zeg: ik zoek bescherming bij de Heer van de mensen'],
     ['مَلِكِ النَّاسِ','Maliki n-nas','De Koning van de mensen'],
     ['إِلَٰهِ النَّاسِ','Ilahi n-nas','De God van de mensen'],
     ['مِن شَرِّ الْوَسْوَاسِ الْخَنَّاسِ','Min sharri l-waswasi l-khannas','Tegen het kwaad van de influisteraar die zich terugtrekt'],
     ['الَّذِي يُوَسْوِسُ فِي صُدُورِ النَّاسِ','Alladhi yuwaswisu fi suduri n-nas','Die influistert in de harten van de mensen'],
     ['مِنَ الْجِنَّةِ وَالنَّاسِ','Mina l-jinnati wa n-nas','Van de jinn en de mensen']]},

 {id:'h-falaq', naam:'Al-Falaq', ar:'الفلق', nr:113, aya:5, soort:'soera', waarom:'Samen met an-Nas: de twee beschermers.',
  r:[['قُلْ أَعُوذُ بِرَبِّ الْفَلَقِ','Qul a\'udhu bi-rabbi l-falaq','Zeg: ik zoek bescherming bij de Heer van de dageraad'],
     ['مِن شَرِّ مَا خَلَقَ','Min sharri ma khalaq','Tegen het kwaad van wat Hij geschapen heeft'],
     ['وَمِن شَرِّ غَاسِقٍ إِذَا وَقَبَ','Wa min sharri ghasiqin idha waqab','En tegen het kwaad van de duisternis wanneer die invalt'],
     ['وَمِن شَرِّ النَّفَّاثَاتِ فِي الْعُقَدِ','Wa min sharri n-naffathati fi l-\'uqad','En tegen het kwaad van hen die op knopen blazen'],
     ['وَمِن شَرِّ حَاسِدٍ إِذَا حَسَدَ','Wa min sharri hasidin idha hasad','En tegen het kwaad van een jaloerse wanneer hij jaloers is']]},

 {id:'h-ikhlas', naam:'Al-Ikhlas', ar:'الإخلاص', nr:112, aya:4, soort:'soera', waarom:'Een derde van de Koran waard, zei de Profeet ﷺ.',
  r:[['قُلْ هُوَ اللَّهُ أَحَدٌ','Qul huwa llahu ahad','Zeg: Hij is Allah, de Enige'],
     ['اللَّهُ الصَّمَدُ','Allahu s-samad','Allah, tot wie alles zich wendt'],
     ['لَمْ يَلِدْ وَلَمْ يُولَدْ','Lam yalid wa lam yulad','Hij heeft niet verwekt en is niet verwekt'],
     ['وَلَمْ يَكُن لَّهُ كُفُوًا أَحَدٌ','Wa lam yakun lahu kufuwan ahad','En niemand is aan Hem gelijk']]},

 {id:'h-masad', naam:'Al-Masad', ar:'المسد', nr:111, aya:5, soort:'soera', waarom:'Kort, met een duidelijk ritme.',
  r:[['تَبَّتْ يَدَا أَبِي لَهَبٍ وَتَبَّ','Tabbat yada abi lahabin wa tabb','Vergaan zijn de handen van Abu Lahab, en hijzelf is vergaan'],
     ['مَا أَغْنَىٰ عَنْهُ مَالُهُ وَمَا كَسَبَ','Ma aghna \'anhu maluhu wa ma kasab','Zijn bezit en wat hij verdiende baatten hem niet'],
     ['سَيَصْلَىٰ نَارًا ذَاتَ لَهَبٍ','Sayasla naran dhata lahab','Hij zal een laaiend vuur binnengaan'],
     ['وَامْرَأَتُهُ حَمَّالَةَ الْحَطَبِ','Wa mra\'atuhu hammalata l-hatab','En ook zijn vrouw, de draagster van het brandhout'],
     ['فِي جِيدِهَا حَبْلٌ مِّن مَّسَدٍ','Fi jidiha hablun min masad','Om haar hals een touw van vezels']]},

 {id:'h-nasr', naam:'An-Nasr', ar:'النصر', nr:110, aya:3, soort:'soera', waarom:'Drie regels. Een mooie tweede soera om te leren.',
  r:[['إِذَا جَاءَ نَصْرُ اللَّهِ وَالْفَتْحُ','Idha ja\'a nasru llahi wa l-fath','Wanneer de hulp van Allah komt en de overwinning'],
     ['وَرَأَيْتَ النَّاسَ يَدْخُلُونَ فِي دِينِ اللَّهِ أَفْوَاجًا','Wa ra\'ayta n-nasa yadkhuluna fi dini llahi afwaja','En je de mensen in groepen de godsdienst van Allah ziet binnentreden'],
     ['فَسَبِّحْ بِحَمْدِ رَبِّكَ وَاسْتَغْفِرْهُ إِنَّهُ كَانَ تَوَّابًا','Fasabbih bi-hamdi rabbika wa staghfirh, innahu kana tawwaba','Prijs dan je Heer en vraag Hem om vergeving; Hij aanvaardt het berouw']]},

 {id:'h-kafirun', naam:'Al-Kafirun', ar:'الكافرون', nr:109, aya:6, soort:'soera', waarom:'Wordt vaak gelezen in de sunna van de Fajr.',
  r:[['قُلْ يَا أَيُّهَا الْكَافِرُونَ','Qul ya ayyuha l-kafirun','Zeg: o jullie ongelovigen'],
     ['لَا أَعْبُدُ مَا تَعْبُدُونَ','La a\'budu ma ta\'budun','Ik aanbid niet wat jullie aanbidden'],
     ['وَلَا أَنتُمْ عَابِدُونَ مَا أَعْبُدُ','Wa la antum \'abiduna ma a\'bud','En jullie aanbidden niet wat ik aanbid'],
     ['وَلَا أَنَا عَابِدٌ مَّا عَبَدتُّمْ','Wa la ana \'abidun ma \'abadtum','En ik aanbid niet wat jullie hebben aanbeden'],
     ['وَلَا أَنتُمْ عَابِدُونَ مَا أَعْبُدُ','Wa la antum \'abiduna ma a\'bud','En jullie aanbidden niet wat ik aanbid'],
     ['لَكُمْ دِينُكُمْ وَلِيَ دِينِ','Lakum dinukum wa liya din','Voor jullie jullie godsdienst, en voor mij de mijne']]},

 {id:'h-kawthar', naam:'Al-Kawthar', ar:'الكوثر', nr:108, aya:3, soort:'soera', waarom:'De kortste soera van de Koran.',
  r:[['إِنَّا أَعْطَيْنَاكَ الْكَوْثَرَ','Inna a\'taynaka l-kawthar','Wij hebben jou de overvloed gegeven'],
     ['فَصَلِّ لِرَبِّكَ وَانْحَرْ','Fasalli li-rabbika wa nhar','Bid daarom tot je Heer en offer'],
     ['إِنَّ شَانِئَكَ هُوَ الْأَبْتَرُ','Inna shani\'aka huwa l-abtar','Wie jou haat, hij is het die zonder nageslacht blijft']]},

 {id:'h-maun', naam:'Al-Ma\'un', ar:'الماعون', nr:107, aya:7, soort:'soera', waarom:'Over gebed en gedrag in één adem.',
  r:[['أَرَأَيْتَ الَّذِي يُكَذِّبُ بِالدِّينِ','A ra\'ayta lladhi yukadhdhibu bi-d-din','Heb jij hem gezien die het oordeel ontkent?'],
     ['فَذَٰلِكَ الَّذِي يَدُعُّ الْيَتِيمَ','Fadhalika lladhi yadu\'\'u l-yatim','Dat is degene die de wees wegduwt'],
     ['وَلَا يَحُضُّ عَلَىٰ طَعَامِ الْمِسْكِينِ','Wa la yahuddu \'ala ta\'ami l-miskin','En niet aanspoort om de arme te voeden'],
     ['فَوَيْلٌ لِّلْمُصَلِّينَ','Fawaylun li-l-musallin','Wee dan de biddenden'],
     ['الَّذِينَ هُمْ عَن صَلَاتِهِمْ سَاهُونَ','Alladhina hum \'an salatihim sahun','Die achteloos zijn ten aanzien van hun gebed'],
     ['الَّذِينَ هُمْ يُرَاءُونَ','Alladhina hum yura\'un','Die zich willen laten zien'],
     ['وَيَمْنَعُونَ الْمَاعُونَ','Wa yamna\'una l-ma\'un','En de kleine hulp weigeren']]},

 {id:'h-quraysh', naam:'Quraysh', ar:'قريش', nr:106, aya:4, soort:'soera', waarom:'Hoort bij al-Fil: lees ze achter elkaar.',
  r:[['لِإِيلَافِ قُرَيْشٍ','Li-ilafi quraysh','Vanwege de gewoonte van Quraysh'],
     ['إِيلَافِهِمْ رِحْلَةَ الشِّتَاءِ وَالصَّيْفِ','Ilafihim rihlata sh-shita\'i wa s-sayf','Hun gewoonte van de reis in winter en zomer'],
     ['فَلْيَعْبُدُوا رَبَّ هَٰذَا الْبَيْتِ','Falya\'budu rabba hadha l-bayt','Laat hen dan de Heer van dit Huis aanbidden'],
     ['الَّذِي أَطْعَمَهُم مِّن جُوعٍ وَآمَنَهُم مِّنْ خَوْفٍ','Alladhi at\'amahum min ju\'in wa amanahum min khawf','Die hen voedde tegen de honger en hen veilig maakte voor de angst']]},

 {id:'h-fil', naam:'Al-Fil', ar:'الفيل', nr:105, aya:5, soort:'soera', waarom:'Het verhaal van het jaar van de olifant.',
  r:[['أَلَمْ تَرَ كَيْفَ فَعَلَ رَبُّكَ بِأَصْحَابِ الْفِيلِ','Alam tara kayfa fa\'ala rabbuka bi-ashabi l-fil','Heb jij niet gezien wat jouw Heer met de mannen van de olifant deed?'],
     ['أَلَمْ يَجْعَلْ كَيْدَهُمْ فِي تَضْلِيلٍ','Alam yaj\'al kaydahum fi tadlil','Heeft Hij hun list niet laten mislukken?'],
     ['وَأَرْسَلَ عَلَيْهِمْ طَيْرًا أَبَابِيلَ','Wa arsala \'alayhim tayran ababil','En Hij zond zwermen vogels op hen af'],
     ['تَرْمِيهِم بِحِجَارَةٍ مِّن سِجِّيلٍ','Tarmihim bi-hijaratin min sijjil','Die hen bekogelden met stenen van gebakken klei'],
     ['فَجَعَلَهُمْ كَعَصْفٍ مَّأْكُولٍ','Faja\'alahum ka-\'asfin ma\'kul','En Hij maakte hen als afgevreten kaf']]},

 {id:'h-humaza', naam:'Al-Humaza', ar:'الهمزة', nr:104, aya:9, soort:'soera', waarom:'Stond nog niet in de rij; hij hoort tussen al-Fil en al-\'Asr.',
  r:[['وَيْلٌ لِّكُلِّ هُمَزَةٍ لُّمَزَةٍ','Waylun li-kulli humazatin lumaza','Wee elke lasteraar en roddelaar'],
     ['الَّذِي جَمَعَ مَالًا وَعَدَّدَهُ','Alladhi jama\'a malan wa \'addadah','Die bezit bijeenbrengt en het telkens telt'],
     ['يَحْسَبُ أَنَّ مَالَهُ أَخْلَدَهُ','Yahsabu anna malahu akhladah','En daarbij denkt dat zijn bezit hem onsterfelijk maakt'],
     ['كَلَّا لَيُنبَذَنَّ فِي الْحُطَمَةِ','Kalla la-yunbadhanna fi l-hutama','Welnee, hij wordt in de verbrijzelaar gesmeten'],
     ['وَمَا أَدْرَاكَ مَا الْحُطَمَةُ','Wa ma adraka ma l-hutama','En hoe kom jij te weten wat de verbrijzelaar is?'],
     ['نَارُ اللَّهِ الْمُوقَدَةُ','Naru llahi l-muqada','Het aangestoken vuur van Allah'],
     ['الَّتِي تَطَّلِعُ عَلَى الْأَفْئِدَةِ','Allati tattali\'u \'ala l-af\'ida','Dat tot in de harten doordringt'],
     ['إِنَّهَا عَلَيْهِم مُّؤْصَدَةٌ','Innaha \'alayhim mu\'sada','Het zal zich boven hen sluiten'],
     ['فِي عَمَدٍ مُّمَدَّدَةٍ','Fi \'amadin mumaddada','In langgerekte zuilen']]},

 {id:'h-asr', naam:'Al-\'Asr', ar:'العصر', nr:103, aya:3, soort:'soera', waarom:'Drie regels waarin de hele islam past.',
  r:[['وَالْعَصْرِ','Wa l-\'asr','Bij de tijd'],
     ['إِنَّ الْإِنسَانَ لَفِي خُسْرٍ','Inna l-insana lafi khusr','De mens lijdt werkelijk verlies'],
     ['إِلَّا الَّذِينَ آمَنُوا وَعَمِلُوا الصَّالِحَاتِ وَتَوَاصَوْا بِالْحَقِّ وَتَوَاصَوْا بِالصَّبْرِ','Illa lladhina amanu wa \'amilu s-salihati wa tawasaw bi-l-haqqi wa tawasaw bi-s-sabr','Behalve zij die geloven, het goede doen, elkaar aansporen tot de waarheid en elkaar aansporen tot geduld']]},

 {id:'h-tashahhud', naam:'De tashahhud', ar:'التشهد', soort:'gebed', waarom:'In elke zitting van elk gebed. Na al-Fatiha het belangrijkst.',
  r:[['التَّحِيَّاتُ لِلَّهِ، الزَّاكِيَاتُ لِلَّهِ','At-tahiyyatu lillah, az-zakiyatu lillah','De groeten zijn voor Allah, de reine daden zijn voor Allah'],
     ['الطَّيِّبَاتُ الصَّلَوَاتُ لِلَّهِ','At-tayyibatu s-salawatu lillah','De goede woorden en de gebeden zijn voor Allah'],
     ['السَّلَامُ عَلَيْكَ أَيُّهَا النَّبِيُّ وَرَحْمَةُ اللَّهِ وَبَرَكَاتُهُ','As-salamu \'alayka ayyuha n-nabiyyu wa rahmatu llahi wa barakatuh','Vrede zij met jou, o profeet, en de barmhartigheid van Allah en Zijn zegeningen'],
     ['السَّلَامُ عَلَيْنَا وَعَلَىٰ عِبَادِ اللَّهِ الصَّالِحِينَ','As-salamu \'alayna wa \'ala \'ibadi llahi s-salihin','Vrede zij met ons en met de oprechte dienaren van Allah'],
     ['أَشْهَدُ أَنْ لَا إِلَٰهَ إِلَّا اللَّهُ وَحْدَهُ لَا شَرِيكَ لَهُ','Ashhadu an la ilaha illa llahu wahdahu la sharika lah','Ik getuig dat er geen god is dan Allah alleen, zonder deelgenoot'],
     ['وَأَشْهَدُ أَنَّ مُحَمَّدًا عَبْدُهُ وَرَسُولُهُ','Wa ashhadu anna Muhammadan \'abduhu wa rasuluh','En ik getuig dat Mohammed Zijn dienaar en boodschapper is']]},

 {id:'h-salawat', naam:'De salawat', ar:'الصلاة الإبراهيمية', soort:'gebed', waarom:'In de laatste zitting, na de tashahhud.',
  r:[['اللَّهُمَّ صَلِّ عَلَىٰ مُحَمَّدٍ وَعَلَىٰ آلِ مُحَمَّدٍ','Allahumma salli \'ala Muhammadin wa \'ala ali Muhammad','Allah, zegen Mohammed en de familie van Mohammed'],
     ['كَمَا صَلَّيْتَ عَلَىٰ إِبْرَاهِيمَ وَعَلَىٰ آلِ إِبْرَاهِيمَ','Kama sallayta \'ala Ibrahima wa \'ala ali Ibrahim','Zoals U Ibrahim en de familie van Ibrahim gezegend hebt'],
     ['وَبَارِكْ عَلَىٰ مُحَمَّدٍ وَعَلَىٰ آلِ مُحَمَّدٍ','Wa barik \'ala Muhammadin wa \'ala ali Muhammad','En geef zegen aan Mohammed en de familie van Mohammed'],
     ['كَمَا بَارَكْتَ عَلَىٰ إِبْرَاهِيمَ وَعَلَىٰ آلِ إِبْرَاهِيمَ','Kama barakta \'ala Ibrahima wa \'ala ali Ibrahim','Zoals U Ibrahim en zijn familie gezegend hebt'],
     ['فِي الْعَالَمِينَ إِنَّكَ حَمِيدٌ مَجِيدٌ','Fi l-\'alamina innaka hamidun majid','In alle werelden. U bent de Geprezene, de Verhevene']]},

 {id:'h-dhikr', naam:'De woorden in het gebed', ar:'أذكار الصلاة', soort:'gebed', waarom:'Wat je zegt in de buiging, bij het opkomen en in de knieval.',
  r:[['سُبْحَانَ رَبِّيَ الْعَظِيمِ','Subhana rabbiya l-\'azim','Volmaakt is mijn Heer, de Geweldige — in de buiging','soeb-HAA-na RAB-bi-ya l-‘a-DHIEM'],
     ['سَمِعَ اللَّهُ لِمَنْ حَمِدَهُ','Sami\'a llahu liman hamidah','Allah hoort wie Hem prijst — bij het opkomen','sa-MI-‘a l-LAA-hoe LI-man HA-mi-dah'],
     ['رَبَّنَا وَلَكَ الْحَمْدُ','Rabbana wa laka l-hamd','Onze Heer, aan U komt alle lof toe — als je rechtop staat','RAB-ba-naa wa LA-ka l-HAMD'],
     ['سُبْحَانَ رَبِّيَ الْأَعْلَى','Subhana rabbiya l-a\'la','Volmaakt is mijn Heer, de Allerhoogste — in de knieval','soeb-HAA-na RAB-bi-ya l-A‘-laa'],
     ['رَبِّ اغْفِرْ لِي','Rabbi ghfir li','Heer, vergeef mij — tussen de twee knievallen','RAB-bigh-FIR lie']]},
 {id:'h-iqama', naam:'De iqama', ar:'الإقامة', soort:'gebed', waarom:'De oproep vlak voordat het gebed begint. Tien zinnen, elk één keer — behalve de takbir.',
  r:[['اللَّهُ أَكْبَرُ، اللَّهُ أَكْبَرُ','Allahu akbar, Allahu akbar','Allah is groter, Allah is groter','al-LAA-hoe AK-bar · al-LAA-hoe AK-bar'],
     ['أَشْهَدُ أَنْ لَا إِلَٰهَ إِلَّا اللَّهُ','Ashhadu an la ilaha illa llah','Ik getuig dat er geen god is dan Allah','asj-HA-doe an laa i-LAA-ha il-la l-LAAH'],
     ['أَشْهَدُ أَنَّ مُحَمَّدًا رَسُولُ اللَّهِ','Ashhadu anna Muhammadan rasulu llah','Ik getuig dat Mohammed de boodschapper van Allah is','asj-HA-doe AN-na moe-HAM-ma-dan ra-SOE-loe l-LAAH'],
     ['حَيَّ عَلَى الصَّلَاةِ','Hayya \'ala s-salah','Kom naar het gebed','HAY-ya ‘a-la s-sa-LAAH'],
     ['حَيَّ عَلَى الْفَلَاحِ','Hayya \'ala l-falah','Kom naar wat je redt','HAY-ya ‘a-la l-fa-LAAH'],
     ['قَدْ قَامَتِ الصَّلَاةُ','Qad qamati s-salah','Het gebed begint nu','qad QAA-ma-ti s-sa-LAAH'],
     ['اللَّهُ أَكْبَرُ، اللَّهُ أَكْبَرُ','Allahu akbar, Allahu akbar','Allah is groter, Allah is groter','al-LAA-hoe AK-bar · al-LAA-hoe AK-bar'],
     ['لَا إِلَٰهَ إِلَّا اللَّهُ','La ilaha illa llah','Er is geen god dan Allah','laa i-LAA-ha il-la l-LAAH']]},
 {id:'h-nagebed', naam:'Na het gebed', ar:'أذكار بعد الصلاة', soort:'gebed', waarom:'Wat je zegt als je na de slotgroet nog even blijft zitten.',
  r:[['أَسْتَغْفِرُ اللَّهَ','Astaghfiru llah','Ik vraag Allah om vergeving — drie keer','as-tagh-FI-roe l-LAAH'],
     ['اللَّهُمَّ أَنْتَ السَّلَامُ وَمِنْكَ السَّلَامُ، تَبَارَكْتَ يَا ذَا الْجَلَالِ وَالْإِكْرَامِ','Allahumma anta s-salamu wa minka s-salam, tabarakta ya dha l-jalali wa l-ikram','Allah, U bent de Vrede en van U komt de vrede; gezegend bent U, Bezitter van majesteit en eer'],
     ['سُبْحَانَ اللَّهِ','Subhana llah','Volmaakt is Allah — 33 keer','soeb-HAA-na l-LAAH'],
     ['الْحَمْدُ لِلَّهِ','Alhamdu lillah','Alle lof is voor Allah — 33 keer','al-HAM-doe lil-LAAH'],
     ['اللَّهُ أَكْبَرُ','Allahu akbar','Allah is groter — 33 keer','al-LAA-hoe AK-bar'],
     ['لَا إِلَٰهَ إِلَّا اللَّهُ وَحْدَهُ لَا شَرِيكَ لَهُ، لَهُ الْمُلْكُ وَلَهُ الْحَمْدُ وَهُوَ عَلَىٰ كُلِّ شَيْءٍ قَدِيرٌ','La ilaha illa llahu wahdahu la sharika lah, lahu l-mulku wa lahu l-hamdu wa huwa \'ala kulli shay\'in qadir','Er is geen god dan Allah alleen, zonder deelgenoot — als honderdste']]},
 {id:'h-dua-salam', naam:'De du\'a vóór de slotgroet', ar:'دعاء قبل السلام', soort:'gebed', waarom:'Het laatste dat je zegt terwijl je nog in het gebed zit.',
  r:[['اللَّهُمَّ إِنِّي أَعُوذُ بِكَ مِنْ عَذَابِ جَهَنَّمَ','Allahumma inni a\'udhu bika min \'adhabi jahannam','Allah, ik zoek bij U bescherming tegen de straf van de hel'],
     ['وَمِنْ عَذَابِ الْقَبْرِ','wa min \'adhabi l-qabr','en tegen de straf van het graf'],
     ['وَمِنْ فِتْنَةِ الْمَحْيَا وَالْمَمَاتِ','wa min fitnati l-mahya wa l-mamat','en tegen de beproeving van het leven en de dood'],
     ['وَمِنْ شَرِّ فِتْنَةِ الْمَسِيحِ الدَّجَّالِ','wa min sharri fitnati l-masihi d-dajjal','en tegen het kwaad van de beproeving van de valse messias']]}
];

/* Du'a's voor de dag. */
export const DUAS: Dua[] = [
 {w:'Bij het wakker worden', ar:'الْحَمْدُ لِلَّهِ الَّذِي أَحْيَانَا بَعْدَ مَا أَمَاتَنَا وَإِلَيْهِ النُّشُورُ', tr:'Alhamdu lillahi lladhi ahyana ba\'da ma amatana wa ilayhi n-nushur', nl:'Alle lof is voor Allah, die ons weer leven gaf nadat Hij ons had laten sterven; tot Hem is de terugkeer.'},
 {w:'Het toilet in', ar:'اللَّهُمَّ إِنِّي أَعُوذُ بِكَ مِنَ الْخُبُثِ وَالْخَبَائِثِ', tr:'Allahumma inni a\'udhu bika mina l-khubuthi wa l-khaba\'ith', nl:'Allah, ik zoek bij U bescherming tegen het kwade.'},
 {w:'Het toilet uit', ar:'غُفْرَانَكَ', tr:'Ghufranak', nl:'Uw vergeving.'},
 {w:'Voor het eten', ar:'بِسْمِ اللَّهِ', tr:'Bismillah', nl:'In de naam van Allah. (Vergeten? Zeg dan: bismillahi awwalahu wa akhirah.)'},
 {w:'Na het eten', ar:'الْحَمْدُ لِلَّهِ الَّذِي أَطْعَمَنَا وَسَقَانَا وَجَعَلَنَا مُسْلِمِينَ', tr:'Alhamdu lillahi lladhi at\'amana wa saqana wa ja\'alana muslimin', nl:'Alle lof is voor Allah, die ons te eten en te drinken gaf en ons moslim maakte.'},
 {w:'Het huis uit', ar:'بِسْمِ اللَّهِ تَوَكَّلْتُ عَلَى اللَّهِ وَلَا حَوْلَ وَلَا قُوَّةَ إِلَّا بِاللَّهِ', tr:'Bismillah, tawakkaltu \'ala llah, wa la hawla wa la quwwata illa billah', nl:'In de naam van Allah, ik vertrouw op Allah; er is geen kracht en geen macht behalve bij Allah.'},
 {w:'De moskee in', ar:'اللَّهُمَّ افْتَحْ لِي أَبْوَابَ رَحْمَتِكَ', tr:'Allahumma ftah li abwaba rahmatik', nl:'Allah, open voor mij de poorten van Uw barmhartigheid.'},
 {w:'De moskee uit', ar:'اللَّهُمَّ إِنِّي أَسْأَلُكَ مِنْ فَضْلِكَ', tr:'Allahumma inni as\'aluka min fadlik', nl:'Allah, ik vraag U van Uw gunst.'},
 {w:'Voor het slapen', ar:'بِاسْمِكَ اللَّهُمَّ أَمُوتُ وَأَحْيَا', tr:'Bismika llahumma amutu wa ahya', nl:'In Uw naam, Allah, sterf ik en leef ik.'},
 {w:'Voor je ouders', ar:'رَبِّ ارْحَمْهُمَا كَمَا رَبَّيَانِي صَغِيرًا', tr:'Rabbi rhamhuma kama rabbayani saghira', nl:'Heer, wees barmhartig voor hen zoals zij mij grootbrachten toen ik klein was.'},
 {w:'Als je iets moeilijks moet doen', ar:'رَبِّ اشْرَحْ لِي صَدْرِي وَيَسِّرْ لِي أَمْرِي', tr:'Rabbi shrah li sadri wa yassir li amri', nl:'Heer, verruim mijn borst en maak mijn taak gemakkelijk voor mij.'},
 {w:'Als je iets wilt vragen voor deze en de volgende wereld', ar:'رَبَّنَا آتِنَا فِي الدُّنْيَا حَسَنَةً وَفِي الْآخِرَةِ حَسَنَةً وَقِنَا عَذَابَ النَّارِ', tr:'Rabbana atina fi d-dunya hasanatan wa fi l-akhirati hasanatan wa qina \'adhaba n-nar', nl:'Onze Heer, geef ons in deze wereld het goede en in het hiernamaals het goede, en bescherm ons tegen de straf van het vuur.'},
 {w:'Als je iemand hoort niezen', ar:'يَرْحَمُكَ اللَّهُ', tr:'Yarhamuka llah', nl:'Moge Allah je barmhartig zijn. (Wie niest zegt eerst: alhamdulillah.)'},
 {w:'Als je op reis gaat', ar:'سُبْحَانَ الَّذِي سَخَّرَ لَنَا هَٰذَا وَمَا كُنَّا لَهُ مُقْرِنِينَ', tr:'Subhana lladhi sakhkhara lana hadha wa ma kunna lahu muqrinin', nl:'Volmaakt is Hij die dit voor ons dienstbaar maakte; wij hadden dat zelf niet gekund.'},
 {w:'Als je iets vergeten bent of spijt hebt', ar:'أَسْتَغْفِرُ اللَّهَ', tr:'Astaghfiru llah', nl:'Ik vraag Allah om vergeving.'}
];
