-- Uitvoerrechten, zoals ze in het bronproject staan.
revoke execute on all functions in schema public from public, anon, authenticated;
alter default privileges in schema public revoke execute on functions from public, anon, authenticated;

grant execute on function public.bennahub_accounts(p_app text) to anon, authenticated;
grant execute on function public.bennahub_fotos(p_gezin text, p_naam text, p_code text) to anon, authenticated;
grant execute on function public.bennahub_gezin_start(p_gezin text, p_wachtwoord text, p_leden jsonb) to anon, authenticated;
grant execute on function public.bennahub_gezin_wachtwoord(p_gezin text, p_oud text, p_nieuw text) to anon, authenticated;
grant execute on function public.bennahub_leden_lijst(p_gezin text) to anon, authenticated;
grant execute on function public.bennahub_lid_aanmelden(p_gezin text, p_naam text, p_code text) to anon, authenticated;
grant execute on function public.bennahub_lid_code(p_gezin text, p_naam text, p_oud text, p_nieuw text) to anon, authenticated;
grant execute on function public.bennahub_lid_foto(p_gezin text, p_naam text, p_code text, p_foto text) to anon, authenticated;
grant execute on function public.bennahub_lid_geboren(p_gezin text, p_ouder_ww text, p_naam text, p_jaar integer) to anon, authenticated;
grant execute on function public.bennahub_lid_reset(p_gezin text, p_ouder_ww text, p_naam text) to anon, authenticated;
grant execute on function public.bennahub_lid_zet(p_gezin text, p_ouder_ww text, p_naam text, p_rol text, p_emoji text, p_kleur text, p_apps jsonb, p_actief boolean, p_volgorde integer) to anon, authenticated;
grant execute on function public.bennahub_load(p_app text, p_account text, p_pin text) to anon, authenticated;
grant execute on function public.bennahub_overzicht(p_gezin text, p_ouder_ww text) to anon, authenticated;
grant execute on function public.bennahub_register(p_app text, p_account text, p_pin text, p_data jsonb) to anon, authenticated;
grant execute on function public.bennahub_save(p_app text, p_account text, p_pin text, p_data jsonb) to anon, authenticated;
grant execute on function public.bennahub_wachtwoord(p_app text, p_account text, p_oud text, p_nieuw text) to anon, authenticated;
grant execute on function public.kal_aanmelden(p_account text, p_ww text) to anon, authenticated;
grant execute on function public.kal_afmelden(p_token text) to anon, authenticated;
grant execute on function public.kal_beweging_dag(p_sleutel text, p_datum text, p_stappen text, p_slaap_min text, p_slaap_uur text, p_slaap_sec text, p_actieve_energie_kcal text, p_fiets_min text, p_gewicht_kg text, p_gewicht_bron text, p_dagen_terug text, p_hartslag_rust text) to anon, authenticated;
grant execute on function public.kal_beweging_ontvangen(p_sleutel text, p_dagen jsonb) to anon, authenticated;
grant execute on function public.kal_dag_zetten(p_token text, p_datum date, p_patch jsonb) to anon, authenticated;
grant execute on function public.kal_dagen_importeren(p_token text, p_dagen jsonb) to anon, authenticated;
grant execute on function public.kal_dagstand(p_gebruiker uuid) to anon, authenticated;
grant execute on function public.kal_gerecht(p_token text, p_dish_id uuid) to anon, authenticated;
grant execute on function public.kal_getal(p_tekst text) to anon, authenticated;
grant execute on function public.kal_koppeling_maken(p_token text, p_naam text) to anon, authenticated;
grant execute on function public.kal_koppeling_wissen(p_token text, p_id uuid) to anon, authenticated;
grant execute on function public.kal_koppelingen_lijst(p_token text) to anon, authenticated;
grant execute on function public.kal_maaltijd_bewaren(p_token text, p_naam text, p_toelichting text, p_porties numeric, p_regels jsonb) to anon, authenticated;
grant execute on function public.kal_maaltijd_favoriet(p_token text, p_id uuid, p_aan boolean) to anon, authenticated;
grant execute on function public.kal_maaltijd_wissen(p_token text, p_id uuid) to anon, authenticated;
grant execute on function public.kal_maaltijden(p_token text) to anon, authenticated;
grant execute on function public.kal_modelstand_zetten(p_token text, p_doel_kcal numeric, p_eiwit_doel_g numeric, p_tdee_laag numeric, p_tdee_hoog numeric, p_zekerheid text) to anon, authenticated;
grant execute on function public.kal_ophalen(p_token text, p_vanaf date) to anon, authenticated;
grant execute on function public.kal_portiematen(p_token text, p_nevo_code text) to anon, authenticated;
grant execute on function public.kal_prikkel_bouwen(p_soort text) to anon, authenticated;
grant execute on function public.kal_prikkel_gelogd(p_gebruiker uuid, p_soort text, p_onderwerp text, p_gelukt boolean, p_fout text) to anon, authenticated;
grant execute on function public.kal_profiel_zetten(p_token text, p_patch jsonb) to anon, authenticated;
grant execute on function public.kal_regel_wissen(p_token text, p_id uuid) to anon, authenticated;
grant execute on function public.kal_regels_toevoegen(p_token text, p_regels jsonb) to anon, authenticated;
grant execute on function public.kal_registreren(p_account text, p_ww text, p_naam text) to anon, authenticated;
grant execute on function public.kal_rij_toevoegen(p_token text, p_tabel text, p_rij jsonb) to anon, authenticated;
grant execute on function public.kal_rij_wissen(p_token text, p_tabel text, p_id uuid) to anon, authenticated;
grant execute on function public.kal_sessie(p_token text) to anon, authenticated;
grant execute on function public.kal_weekcijfers(p_gebruiker uuid, p_venster integer) to anon, authenticated;
grant execute on function public.kal_zoeken(p_token text, p_q text, p_limiet integer) to anon, authenticated;
grant execute on function public.oefenapp_ch_create(p_code text, p_data jsonb) to anon, authenticated;
grant execute on function public.oefenapp_ch_get(p_code text) to anon, authenticated;
grant execute on function public.oefenapp_ch_submit(p_code text, p_friend jsonb) to anon, authenticated;
grant execute on function public.oefenapp_load(p_household text, p_pin text) to anon, authenticated;
grant execute on function public.oefenapp_register(p_household text, p_pin text, p_data jsonb) to anon, authenticated;
grant execute on function public.oefenapp_save(p_household text, p_pin text, p_data jsonb) to anon, authenticated;

revoke all on function public.kal_prikkel_bouwen(text) from anon, authenticated;
revoke all on function public.kal_prikkel_gelogd(uuid, text, text, boolean, text) from anon, authenticated;
